### ISSUE TITLE
LoliASM breaks Thermal Expansion's textures and causes crashes

### ISSUE THREAD

**Issue by SirSlender** [LoliKingdom/LoliASM#10]
https://paste.dimdev.org/cokeviwofi.mccrash
Is the crash report. Anytime I go to break a Thermal Expansion machine the game crashes and their textures are no longer showing up correctly as an item (pink and black checkered box), but I can still place and use them.

I also get a constant message to add some string in my config but I don't know what string to add? I add what the console says but it still spouts the same message.

**Comment by Rongmario** [comment]
Can I have the full `latest.log`?

**Comment by SirSlender** [comment]
[2021-05-09-6.log](https://github.com/LoliKingdom/LoliASM/files/6448393/2021-05-09-6.log)

**Comment by Rongmario** [comment]
Try to do that and eliminate all errors then see if you still get the crashes. If not I'll check it out.

**Comment by Rongmario** [comment]
Yeah I think I broke it because of a refactor in 2.3, I'll be fixing it later today, can you test with 2.1 or 2.2?

**Comment by SirSlender** [comment]
This was from 2.2 but I did also try 2.3. I can try testing with 2.1 later today.

**Comment by Rongmario** [comment]
That won't be needed, they don't differ much.

**Comment by Rongmario** [comment]
I haven't had proper time to investigate this but I haven't gotten a crash yet from the times I've tried. For the mean time turn `logClassesThatNeedPatching` off. I've noticed `codechicken.lib.util.VertexDataUtils` isn't being patched properly; hence why the messages still pop up, but shouldn't have anything to do with the crash.

**Comment by Rongmario** [comment]
Try 2.4.1 and see if crashes still occur.

**Comment by magcicada** [comment]
@Rongmario

**Comment by magcicada** [comment]
And after a while, it crashed for the same reason as SirSlender....

**Comment by GBLodb** [comment]
Is there any progress about this issue? I got the same problem.

**Comment by Rongmario** [comment]
This was fixed a long time ago, if you're booting for the first time, simply restart.

**Comment by GBLodb** [comment]
> This was fixed a long time ago, if you're booting for the first time, simply restart. 

Not really, I keep getting the same result after dozens of restart since the mod is installed in my modpack dev environment

**Comment by Rongmario** [comment]
Yes really, nothing I can tell you except for sending me a log.

**Comment by Rongmario** [comment]
Restart your game

**Comment by InsaanNotFound** [comment]
Restarting doesn't even work.

**Comment by ISurrealI** [comment]
It happens because [face](https://github.com/LoliKingdom/LoliASM/blob/master/src/main/java/zone/rong/loliasm/bakedquad/SupportingBakedQuad.java#L36) is null when rendering thermal expansion machine items
