### ISSUE TITLE
Crash on Startup 1.12.2 Loliasm-4.13

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LoliKingdom/LoliASM#101]
Basic Crash Log 
https://gist.github.com/P3rf3ctXZer0/198f115cf08c104084bcbededb79296e

Full Log
https://gist.github.com/P3rf3ctXZer0/7d9d4675cf27995447588f53c71108ba

**Comment by P3rf3ctXZer0** [comment]
The last thing I did was disable TexFix Mod and Vanilla Fix before I disabled those - it was actually working.

**Comment by Rongmario** [comment]
Fixed in 5.0+.

**Comment by P3rf3ctXZer0** [comment]
Where do I find 5.0?
