### ISSUE TITLE
Crash upon entering the world.

### ISSUE THREAD

**Issue by GBLodb** [LoliKingdom/LoliASM#102]
Loaded the game three times, the first two with LoliASM installed crashed, the last one without LoliASM worked fine.
[debug.log](https://gist.github.com/GBLodb/b22bb0f35aa7f34e75d70bfe7189d16c/raw/5337ea66def9fe3587d8c82fa05dcf5185776c6c/debug.log)

**Comment by Rongmario** [comment]
FIxed in 5.0+
