### ISSUE TITLE
Experimental makeEventsSingletons option makes botania crash on client side

### ISSUE THREAD

**Issue by MadProbe** [LoliKingdom/LoliASM#103]
When enabled, the option makes botania crash with NullPointerException on client load.
[Crash log](https://pastebin.com/dkKQtELD)
When disabled, crash disappears.

**Comment by Rongmario** [comment]
Closing as this experimental feature will probably go in the [Forge fork](https://github.com/CleanroomMC/Danvil).

**Comment by Rongmario** [comment]
This has now been fixed.
