### ISSUE TITLE
Maybe Add This PR into LoliASM?

### ISSUE THREAD

**Issue by afanrofl** [LoliKingdom/LoliASM#104]
I saw this PR on VanillaFix's GitHub but it was never accepted. Maybe you could add it into LoliASM if it hasn't been added already?

https://github.com/DimensionalDevelopment/VanillaFix/pull/268#issue-631729545

**Comment by Rongmario** [comment]
Implemented in 76face3

**Comment by afanrofl** [comment]
Thank you very much!
