### ISSUE TITLE
Potential bug with onDemandAnimatedTextures

### ISSUE THREAD

**Issue by Srdjan-V** [LoliKingdom/LoliASM#106]
It might be just botania incompatibility, the videos should demonstrate what i mean
[Videos.zip](https://github.com/LoliKingdom/LoliASM/files/8757638/Videos.zip)

Forgot to mention optifine was not installed

**Comment by Rongmario** [comment]
Closing as #113 will be the main thread for `onDemandAnimatedTextures` issues from now on.
