### ISSUE TITLE
inquiry

### ISSUE THREAD

**Issue by xingchengs** [LoliKingdom/LoliASM#108]
Will the latest version clash with those that have modified the lighting engine? For example, Photoshop, gtceu, etc. there will be no problem when the 4.0 version is used back. The log shows that gtceu, FML, forge have errors

**Comment by Exaxxion** [comment]
Not sure what this "Photoshop" mod is but at least anecdotally I can say that I have encountered no issues to date with v5.3 and GTCEu 2.3.0.

**Comment by Rongmario** [comment]
Would need any log or crash files you may have to see whats going on.

**Comment by xingchengs** [comment]
I sent it to you by email attachment. I don't know if you received it. The attachment is a crash file. It's OK in version 4.0, but it's wrong after version 5.0



---Original---
From: ***@***.***&gt;
Date: Mon, May 30, 2022 08:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LoliKingdom/LoliASM] inquiry (Issue #108)




 
Would need any log or crash files you may have to see whats going on.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
              
                                        从QQ邮箱发来的超大附件                      
                                                                                        
                               crash-2022-05-30_13.32.20-client.txt (33.50K, 无限期)                                                       进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=9ecd13301c4e8cc8acbe48306134366563b4663063343665441d54555503505054014b075b525748550355014e555757521f04025207555c5206000050031265024007430b19045553004b00561905553e03551e50061857511f055c0a5158114f461e4477b5ab83fac9d3b3eaaa0153a37489a7dd4ca7f54e&t=exs_ftn_download&code=a2f0c46e

**Comment by ghzdude** [comment]
You should be able to drag and drop the crash file into GitHub itself instead of as an email attachment.

**Comment by xingchengs** [comment]
[crash-2022-05-30_13.57.18-client.txt](https://github.com/LoliKingdom/LoliASM/files/8795933/crash-2022-05-30_13.57.18-client.txt)

**Comment by xingchengs** [comment]
[crash-2022-05-30_13.32.20-client.txt](https://github.com/LoliKingdom/LoliASM/files/8795976/crash-2022-05-30_13.32.20-client.txt)

**Comment by xingchengs** [comment]
Is there any new progress on this issue?

**Comment by Rongmario** [comment]
Can't replicate with latest, can you show me your `latest.log` when this is happening?

**Comment by xingchengs** [comment]
---Original---
From: ***@***.***&gt;
Date: Mon, May 30, 2022 14:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LoliKingdom/LoliASM] inquiry (Issue #108)




 
You should be able to drag and drop the crash file into GitHub itself instead of as an email attachment.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
 
              
                                        从QQ邮箱发来的超大附件                      
                                                                                        
                               Desktop.rar (114.72K, 无限期)                                                       进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=cdc969631e18d894ffba1b6363626239d2fc34636162623917195057545757585100185204515a14060300534c03000c0a1b53540753550f570351555153693976534608150d121740574777e0fea4a01b37c0c18b456ad356d0a50b9ea19752&t=exs_ftn_download&code=265cabb9

**Comment by Rongmario** [comment]
Remove VanillaFix.
