### ISSUE TITLE
Fire not animated

### ISSUE THREAD

**Issue by Artronah1** [LoliKingdom/LoliASM#109]
Installed mods: !mixinbooter-4.2.jar, loliasm-5.3.jar, OptiFine_1.12.2_HD_U_G5.jar
In optifine animation not turn off.
https://user-images.githubusercontent.com/106379240/170877257-fcb3c6fc-cb8d-4208-8c87-07e90042929c.mp4

**Comment by Rongmario** [comment]
If you have OptiFine installed, turn on its `Smart Animation` and disable my `onDemandAnimatedTextures`.

**Comment by Artronah1** [comment]
Thank you. That helped!
