### ISSUE TITLE
Not animated textures.

### ISSUE THREAD

**Issue by Pineappleguy03** [LoliKingdom/LoliASM#112]
Issue that I came across. It disables all moving textures... And even when I turn it off. It starts to heavily lag. You should let some animated textures be loaded in. Like Visible Blocks.

**Comment by Pineappleguy03** [comment]
Another Note is that it disables ALL animated textures. Like Fire.

**Comment by Rongmario** [comment]
Cannot replicate, are you using Optifine?

**Comment by Pineappleguy03** [comment]
I am indeed using Optifine. But Animated Textures is on.

**Comment by Rongmario** [comment]
Duplicate of #109
