### ISSUE TITLE
Playerskin Missing Textures

### ISSUE THREAD

**Issue by SenZ01** [LoliKingdom/LoliASM#114]
### **I have no proof that this is loliasm's fault, after removing loliasm the skin appeared to be normal again.**
![image](https://user-images.githubusercontent.com/74424517/172270999-721f2aef-dd62-4706-b9cb-dc1ff7becb61.png)

**Comment by Rongmario** [comment]
Do you have any player skin mods installed? Send your mod list + log files thanks.

**Comment by SenZ01** [comment]
Nope, i don't have any mods installed for skins, here is my current mod list.

https://paste.gg/p/anonymous/accbd04ad103402d8e74c3c0a7d0325b

**Comment by Rongmario** [comment]
Any log files?
I had a quick glance, could be CosmeticArmorReworked, I'll try to check as well.

**Comment by SenZ01** [comment]
i can still send you the logs if you want, just client or server aswell?

**Comment by Rongmario** [comment]
Client but preferably when the client is experiencing said issues.

**Comment by SenZ01** [comment]
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8871589/debug.log)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8871590/latest.log)

**Comment by SenZ01** [comment]
Maybe those logs will have better results as it just happened, my skin texture is broken again

**Comment by 623667595** [comment]
我也是和他一样情况 玩家也会这样

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/175538446-55757143-88a5-4d70-aa84-61d0191f8513.png)

**Comment by Rongmario** [comment]
Try turning off `fixMC186052` in the configs.

**Comment by 623667595** [comment]
> Try turning off `fixMC186052` in the configs.

改完了 貌似没事了

**Comment by 623667595** [comment]
> Try turning off `fixMC186052` in the configs.

改完了 貌似没事了

**Comment by 623667595** [comment]
服务端里不用关闭吧

**Comment by Rongmario** [comment]
不用

**Comment by TrapStoner** [comment]
I just got this issue after adding loliasm 5.4 on the server and joining that server... Haven't seen it before when it was on the client only. After server and client restart skin is back.
