### ISSUE TITLE
Crash log   GTCEU

### ISSUE THREAD

**Issue by xingchengs** [LoliKingdom/LoliASM#115]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8884174/latest.log)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8884175/debug.log)

**Comment by brachy84** [comment]
That doesnt seem to be related to censored asm. It looks like it cant find JEI

**Comment by xingchengs** [comment]
> That doesnt seem to be related to censored asm. It looks like it cant find JEI

Sorry, I made this stupid mistake. I'm trying

**Comment by xingchengs** [comment]
The crash still exist
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8884182/debug.log)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8884183/latest.log)
s

**Comment by brachy84** [comment]
You installed JEID not JEI

**Comment by htmlcsjs** [comment]
install [JEI](https://www.curseforge.com/minecraft/mc-mods/jei) not JEID

**Comment by htmlcsjs** [comment]
or [HEI](https://www.curseforge.com/minecraft/mc-mods/had-enough-items) should work

**Comment by xingchengs** [comment]
According to what you said, it has been working normally. Thank you

**Comment by xingchengs** [comment]
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8884215/debug.log)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8884218/latest.log)
What do you think about this complex crash log???

**Comment by xingchengs** [comment]
I have solved the problem. It should be the problem that mod obtains network packets
