### ISSUE TITLE
[Feature Req.] Remove Narration Button

### ISSUE THREAD

**Issue by 623667595** [LoliKingdom/LoliASM#116]
能不能出一个功能直接删除或者禁用我的世界的复述功能，99%的人都用不到，键位多了 还容易误点

**Comment by clementtttttttt** [comment]
translation: add a way to remove narration since 99% of people wont use it anyway

**Comment by Rongmario** [comment]
Don't worry, I understand Chinese. I'll think about implementing this.

**Comment by 623667595** [comment]
有希望没，那个功能太烦了，按键里还关不掉

**Comment by 623667595** [comment]
有没有希望添加流畅加载mods的功能 。他的构建站https://github.com/UltimateBoomer/mc-smoothboot/tree/1.12-forge
这mods1.12.2弃坑了

**Comment by Rongmario** [comment]
SmoothBoot在1.12.2不會有用途喔

**Comment by Rongmario** [comment]
More suited for [UniversalTweaks](https://github.com/ACGaming/UniversalTweaks), 推給UT了 ^^
