### ISSUE TITLE
Question - Does this do what fast furnace and workbench do?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LoliKingdom/LoliASM#12]
I am curious if there are certain functions this mod does that others are not? Could you make a list of things this mod does that other mods do to prevent any conflicts?

**Comment by Rongmario** [comment]
I'll mention it in the changelog, in the README and on curseforge page if there are any incompatibilities. Most of them are directly prevented in code (e.g. `bakedQuadsSquasher` not turning on when Optifine is installed.)
