### ISSUE TITLE
Putting down Cyberware Surgery Chamber cause serious lag.

### ISSUE THREAD

**Issue by GBLodb** [LoliKingdom/LoliASM#122]
After put down a cyberware surgery chamber, the model animation seems not playing, and the game started to run at about a few seconds per frame, but still able to break the chamber and return to normal FPS. After disabling LoliASM, the problem never return.

Running LoliASM 5.4, cyberware-1.12.2-0.2.11.29(Robotic Parts), forge 2860.
[debug.log](https://github.com/LoliKingdom/LoliASM/files/9165611/debug.log)

**Comment by Rongmario** [comment]
Could you provide a spark profile report?

**Comment by Rongmario** [comment]
Not really, but try to keep the interval short

**Comment by Rongmario** [comment]
Needs testing and reopening issue if this is still present.
