### ISSUE TITLE
服务器崩溃

### ISSUE THREAD

**Issue by NnnBbon** [LoliKingdom/LoliASM#126]
崩溃报告如下：
[crash-reports.zip](https://github.com/LoliKingdom/LoliASM/files/9257761/crash-reports.zip)
日志：
[2022-08-03-6.zip](https://github.com/LoliKingdom/LoliASM/files/9257770/2022-08-03-6.zip)
后台报错：Failed to save chunk java.util.ConcurrentModificationException: null

服务器装有区块限制类插件，需要扫描区块，但实在不明白与“save chunk”有什么联系
求作者大佬帮忙看看我该如何设置loliasm的配置文件！
我已经离不开这个优秀的mod了！

**Comment by Rongmario** [comment]
試試看用 [RandomPatches](https://www.curseforge.com/minecraft/mc-mods/randompatches-forge)

**Comment by NnnBbon** [comment]
谢谢！昨天加上之后服务器目前还没蹦过！

**Comment by NnnBbon** [comment]
好吧....还是崩了，只是没发
[crash-2022-08-05_12.20.00-server.txt](https://github.com/LoliKingdom/LoliASM/files/9266006/crash-2022-08-05_12.20.00-server.txt)
现

**Comment by Rongmario** [comment]
抱歉很久沒回, 如果還有log可以寄過來嗎?

**Comment by NnnBbon** [comment]
感谢你的回信，目前我已经弃用了区块限制插件。在后续可能会继续使用其他插件代替，届时有问题我会第一时间与你联系
