### ISSUE TITLE
Fix difficulty resetting and losing lock status when changing dimension

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [LoliKingdom/LoliASM#128]
As discussed on discord, I am making an issue for this so it could possibly be added as an improvement.

This is specifically: Difficulty changing away from what it was set as when the player changes dimension, losing lock status if the lock was applied.

The related Vanilla MC issue is here: https://bugs.mojang.com/browse/MC-44471 which deals with the lock status resetting, and I think with the difficulty changing.

**Comment by Rongmario** [comment]
Fixed in UT
