### ISSUE TITLE
applied energistics 2

### ISSUE THREAD

**Issue by criscky** [LoliKingdom/LoliASM#13]
i saw this in the log, so i'm reporting, i'm not sure if you need the full log

[10:04:30] [Chunk Batcher 3/WARN] [LoliASM]: class appeng.client.render.model.AutoRotatingModel needs their BakedQuad calls redirecting! Insert the string into config/loliasm.json and report to Rongmario.

**Comment by criscky** [comment]
Just to complement, those are the classes i had to put in the configs
```
        appeng.client.render.model.AutoRotatingModel
        appeng.client.render.cablebus.QuadRotator
        codechicken.lib.render.buffer.BakingVertexBuffer
        com.rwtema.extrautils2.backend.model.Box
        thaumcraft.client.lib.obj.MeshModel
```

**Comment by Rongmario** [comment]
Thank you! Added to [the wiki page](https://github.com/LoliKingdom/LoliASM/wiki/Config-Option---classesThatCallBakedQuadCtor).
