### ISSUE TITLE
onDemandAnimatedTextures disables animation when OptiFine/Nothirium is installed

### ISSUE THREAD

**Issue by G1ll0u** [LoliKingdom/LoliASM#130]
Hello,

Everything is on the title. animations doesnt work for any block (torches and fire included) except liquid blocks when onDemandAnimatedTextures setting is activated.

I think it's a mod that I use that causes that.
Here's my [report](https://mclo.gs/iNjn2Ys) :

<details>
  <summary>REPORT</summary>

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// My bad.

Time: 2022-08-17 21:18:55 CEST
Description: Manually triggered client-side debug crash

java.lang.Throwable
    at net.minecraft.client.Minecraft.redirect$zce000$checkForF3C(Minecraft.java:4739)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:1921)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Jubitus'/1350415, l='MpServer', x=6026.31, y=69.00, z=4072.66]]
  Chunk stats: MultiplayerChunkCache: 4225, 4225
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (176,64,256), Chunk: (at 0,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 48255518 game time, 4256852 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 93 total; [Grim Falko/boy/1778253979455275995/6021/95/4074, Borglinde Falko/wife/8850626462514820053/6020/94/4073, MoCEntityAnt['Ant'/1350412, l='MpServer', x=6104.03, y=67.00, z=4149.50], EntityItem['item.item.egg'/1350414, l='MpServer', x=5981.88, y=67.00, z=4130.09], Grim Erwin/shepherd/3538522827980076103/6010/70/4089, Valborg Hubert/girl/5064232014066387633/6012/93/4093, EntityMule['Mule'/359213, l='MpServer', x=5992.97, y=72.00, z=4091.10], EntityPlayerSP['Jubitus'/1350415, l='MpServer', x=6026.31, y=69.00, z=4072.66], EntitySheep['Mouton'/359215, l='MpServer', x=5987.52, y=77.00, z=4016.23], EntityLatchedRenderer['inconnu'/299, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLlama['Lama'/359214, l='MpServer', x=5988.47, y=77.00, z=4018.19], EntitySheep['Mouton'/359209, l='MpServer', x=5987.86, y=73.00, z=4039.41], EntityChicken['Poule'/359211, l='MpServer', x=5998.45, y=82.00, z=4095.50], MoCEntityTurkey['Turkey'/359210, l='MpServer', x=5981.62, y=70.00, z=4052.72], EntityHorse['Cheval'/1350459, l='MpServer', x=6086.12, y=72.00, z=3997.14], EntityChicken['Poule'/1350190, l='MpServer', x=6000.53, y=82.00, z=4095.86], Baldrik Falko/lumberman/8786821301318349270/6021/94/4073, EntitySheep['Mouton'/1856, l='MpServer', x=6036.07, y=68.00, z=4068.45], EntitySheep['Mouton'/1857, l='MpServer', x=6037.77, y=68.00, z=4069.92], EntitySheep['Mouton'/1858, l='MpServer', x=6037.55, y=68.00, z=4068.45], EntitySheep['Mouton'/1859, l='MpServer', x=6042.96, y=68.00, z=4071.38], EntitySheep['Mouton'/1860, l='MpServer', x=6040.62, y=68.00, z=4068.45], EntitySheep['Mouton'/1861, l='MpServer', x=6036.71, y=68.00, z=4069.36], EntitySheep['Mouton'/1862, l='MpServer', x=6044.19, y=68.00, z=4071.35], EntitySheep['Mouton'/1863, l='MpServer', x=6044.92, y=68.00, z=4069.96], EntitySheep['Mouton'/1864, l='MpServer', x=6041.56, y=68.00, z=4069.78], MoCEntityBee['Bee'/1865, l='MpServer', x=6008.40, y=71.30, z=4087.60], MoCEntityButterfly['ButterFly'/1866, l='MpServer', x=6008.40, y=71.30, z=4087.60], Alwine Hubert/girl/2535992919922849720/6019/95/4079, Gisela Erwin/shepherdf/919396896264027705/6008/73/4084, Sighild Falko/girl/3000857265646946011/6009/89/4091, Bernhilde Erwin/wife/6941451320529798273/6019/82/4076, Roland Hubert/smith/5387672033446808506/6019/95/4077, Ragnhild Erwin/wife/5961037725829473690/6018/95/4075, Bathilde Hubert/wife/125931193309488440/6018/95/4078, Tankred Erwin/boy/7308071840469234769/6022/71/4071, Frank Erwin/guard/795170726357057085/6018/83/4075, EntityGrottol['Grottol'/1406866, l='MpServer', x=6069.50, y=41.00, z=4059.50], EntityChicken['Poule'/432270, l='MpServer', x=5953.54, y=71.00, z=3998.13], MoCEntityMouse['Mouse'/432267, l='MpServer', x=5950.24, y=39.00, z=3996.51], NpcCombat['Soldier'/1350276, l='MpServer', x=6023.57, y=81.41, z=4104.05], EntityDonkey['Âne'/432278, l='MpServer', x=5955.08, y=71.00, z=3999.00], NpcCombat['Soldier'/1350277, l='MpServer', x=6026.59, y=82.00, z=4106.50], EntityCow['Vache'/432279, l='MpServer', x=5959.61, y=71.00, z=3995.45], NpcCombat['Soldier'/1350275, l='MpServer', x=6025.01, y=73.44, z=4109.51], EntityPig['Cochon'/427166, l='MpServer', x=5970.45, y=73.10, z=4088.45], EntityPig['Cochon'/427164, l='MpServer', x=5970.45, y=73.10, z=4088.45], EntityPig['Cochon'/427165, l='MpServer', x=5970.45, y=73.10, z=4088.45], EntityLlama['Lama'/427162, l='MpServer', x=5979.54, y=77.00, z=4023.48], EntityPig['Cochon'/427163, l='MpServer', x=5971.45, y=71.00, z=4087.45], EntityGrottol['Grottol'/1431944, l='MpServer', x=6080.50, y=41.00, z=4125.50], MoCEntityAnt['Ant'/432280, l='MpServer', x=5962.50, y=71.00, z=3996.02], Thilda Erwin/girl/8756972585410017439/6021/69/4071, EntityChicken['Poule'/973729, l='MpServer', x=6001.48, y=82.00, z=4094.81], Helge Hubert/boy/8284732935644804774/6019/95/4076, Roland Erwin/boy/711256047089539245/6013/93/4091, Ingvald Radulf/farmer/4267751431775525139/5972/70/4186, Arnvald Waldemar/lumberman/878181010468060363/5991/70/4195, Wilhelm Hubert/guard/9156075304911445829/6020/95/4077, Sigrune Erwin/girl/3214815646745294175/6020/82/4074, NpcWorker['Worker'/1350352, l='MpServer', x=6019.76, y=79.00, z=4096.01], Sigrune Hubert/wife/486787003355940240/6021/93/4072, MoCEntityHorse['WildHorse'/1350388, l='MpServer', x=6072.05, y=74.00, z=4010.28], MoCEntityHorse['WildHorse'/1350389, l='MpServer', x=6091.94, y=72.00, z=4035.25], EntityItem['item.item.egg'/1440244, l='MpServer', x=5998.44, y=82.00, z=4097.37], EntityDonkey['Âne'/1350391, l='MpServer', x=6082.95, y=72.00, z=4109.94], MoCEntityEnt['Ent'/1350386, l='MpServer', x=6050.97, y=71.00, z=4012.89], EntityLlama['Lama'/1350387, l='MpServer', x=6055.30, y=73.00, z=4126.51], EntityDog['Egg'/490, l='MpServer', x=6006.02, y=69.00, z=4056.04], MoCEntityFly['Fly'/491, l='MpServer', x=6029.10, y=68.00, z=4082.85], MoCEntityEnt['Ent'/1350399, l='MpServer', x=5957.30, y=71.00, z=4151.70], EntityChicken['Poule'/1350392, l='MpServer', x=6086.56, y=88.00, z=4124.92], EntityItem['item.item.egg'/1350393, l='MpServer', x=6085.75, y=88.00, z=4124.13], EntityRabbit['Lapin'/1350394, l='MpServer', x=6080.11, y=90.00, z=4136.36], Dltwin Erwin/guard/7207907710768833987/6020/93/4071, Bathilde Erwin/girl/847240700477336539/6020/95/4078, MoCEntitySalmon['Salmon'/1350372, l='MpServer', x=5947.70, y=62.00, z=4131.30], NpcCombat['Soldier'/1350118, l='MpServer', x=6034.43, y=70.00, z=4107.62], MoCEntityAnt['Ant'/1350374, l='MpServer', x=5947.37, y=71.00, z=4143.00], MoCEntityButterfly['ButterFly'/499, l='MpServer', x=6041.90, y=67.00, z=4082.53], EntityCow['Vache'/1350375, l='MpServer', x=5963.55, y=73.00, z=4055.55], MoCEntityFly['Fly'/500, l='MpServer', x=6041.57, y=67.00, z=4082.45], EntityNewPainting['Painting++'/501, l='MpServer', x=6035.03, y=104.50, z=4090.00], Alfgard Erwin/girl/209277260968270946/6020/69/4070, EntityNewPainting['Painting++'/502, l='MpServer', x=6037.50, y=104.00, z=4093.03], MoCEntitySalmon['Salmon'/1350371, l='MpServer', x=5950.30, y=62.04, z=4130.70], EntityChicken['Poule'/1350381, l='MpServer', x=5986.38, y=69.00, z=4125.45], EntityChicken['Poule'/1350382, l='MpServer', x=5998.79, y=82.00, z=4097.52], MoCEntityAnt['Ant'/1350383, l='MpServer', x=6036.52, y=69.00, z=4015.48], EntityPolarBear['Ours blanc'/1350376, l='MpServer', x=5959.08, y=74.00, z=4059.97], MoCEntityHorse['WildHorse'/1350377, l='MpServer', x=5967.74, y=71.00, z=4104.88], MoCEntityCod['Cod'/1350378, l='MpServer', x=5958.70, y=62.00, z=4123.30], MoCEntityCod['Cod'/1350379, l='MpServer', x=5961.70, y=62.35, z=4129.30]]
  Retry entities: 1 total; [EntityLatchedRenderer['inconnu'/299, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_332, Temurin
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
  Memory: 5673285280 bytes (5410 MB) / 9196535808 bytes (8770 MB) up to 9196535808 bytes (8770 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx9216m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G6_pre1 94 mods loaded, 94 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                      | Source                                                         | Signature                                |
       |:------ |:------------------------ |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                       | minecraft.jar                                                  | None                                     |
       | LCHIJA | mcp                      | 9.42                         | minecraft.jar                                                  | None                                     |
       | LCHIJA | sampler                  | 1.84                         | sampler-1.84.jar                                               | None                                     |
       | LCHIJA | FML                      | 8.0.99.99                    | forge-1.12.2-14.23.5.2859-universal.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2859                 | forge-1.12.2-14.23.5.2859-universal.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy        | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | itemphysic               | 1.4.0                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | littletilescore          | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | otgcore                  | 1.12.2-v9.4                  | minecraft.jar                                                  | None                                     |
       | LCHIJA | mixinbooter              | 5.0                          | minecraft.jar                                                  | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                        | minecraft.jar                                                  | None                                     |
       | LCHIJA | randompatches            | 1.12.2-1.22.1.10             | randompatches-1.12.2-1.22.1.10.jar                             | None                                     |
       | LCHIJA | customskinloader         | 14.14-SNAPSHOT-323           | CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-323.jar            | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
       | LCHIJA | ageofweapons             | 0.13.5                       | Age+of+Weapons+1.12.2++(v.0.13.5).jar                          | None                                     |
       | LCHIJA | aiimprovements           | 0.0.1.3                      | AIImprovements-1.12-0.0.1b3.jar                                | None                                     |
       | LCHIJA | akashictome              | 1.2-12                       | AkashicTome-1.2-12.jar                                         | None                                     |
       | LCHIJA | codechickenlib           | 3.2.3.358                    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ancientwarfare           | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfarestructure  | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfarevehicle    | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfarenpc        | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | ancientwarfareautomation | 1.12.2-2.7.0.772             | ancientwarfare-1.12.2-2.7.0.772.jar                            | None                                     |
       | LCHIJA | applecore                | 3.2.0                        | AppleCore-mc1.12.2-3.2.0.jar                                   | None                                     |
       | LCHIJA | jei                      | 4.16.1.302                   | jei_1.12.2-4.16.1.302.jar                                      | None                                     |
       | LCHIJA | appleskin                | 1.0.9                        | AppleSkin-mc1.12-1.0.9.jar                                     | None                                     |
       | LCHIJA | quark                    | r1.6-179                     | Quark-r1.6-179.jar                                             | None                                     |
       | LCHIJA | autoreglib               | 1.3-32                       | AutoRegLib-1.3-32.jar                                          | None                                     |
       | LCHIJA | ichunutil                | 7.2.2                        | iChunUtil-1.12.2-7.2.2.jar                                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backtools                | 7.0.1                        | BackTools-1.12.2-7.0.1.jar                                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backups                  | 1.5.7                        | Backups-1.12.2-1.5.7.jar                                       | None                                     |
       | LCHIJA | base                     | 3.13.0                       | base-1.12.2-3.13.0.jar                                         | None                                     |
       | LCHIJA | betterthirdperson        | 1.8.1                        | BetterThirdPerson-Forge-1.12.2-1.8.1.jar                       | None                                     |
       | LCHIJA | openterraingenerator     | v9.4                         | OpenTerrainGenerator-1.12.2-v9.4.jar                           | None                                     |
       | LCHIJA | biomebundle              | 5.1                          | Biome_Bundle-1.12.2-v6.1.jar                                   | None                                     |
       | LCHIJA | blockcraftery            | 1.12.2-1.3.1                 | blockcraftery-1.12.2-1.3.1.jar                                 | None                                     |
       | LCHIJA | cfm                      | 6.3.0                        | cfm-6.3.0-mc1.12.2.jar                                         | None                                     |
       | LCHIJA | charm                    | 1.12.2-1.3.7                 | Charm-1.12.2-1.3.7.jar                                         | None                                     |
       | LCHIJA | chickenchunks            | 2.4.2.74                     | ChickenChunks-1.12.2-2.4.2.74-universal.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | chiselsandbits           | 14.33                        | chiselsandbits-14.33.jar                                       | None                                     |
       | LCHIJA | clumps                   | 3.1.2                        | Clumps-3.1.2.jar                                               | None                                     |
       | LCHIJA | comforts                 | 1.4.1.3                      | comforts-1.12.2-1.4.1.3.jar                                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | configmod                | v1.0                         | coroutil-1.12.1-1.2.35.jar                                     | None                                     |
       | LCHIJA | extendedrenderer         | v1.0                         | coroutil-1.12.1-1.2.35.jar                                     | None                                     |
       | LCHIJA | coroutil                 | 1.12.1-1.2.35                | coroutil-1.12.1-1.2.35.jar                                     | None                                     |
       | LCHIJA | corpse                   | 1.12.2-1.0.8                 | corpse-1.12.2-1.0.8.jar                                        | None                                     |
       | LCHIJA | creativecore             | 1.10.0                       | CreativeCore_v1.10.70_mc1.12.2.jar                             | None                                     |
       | LCHIJA | customloadingscreen      | 1.12.2-1.5.7                 | CustomLoadingScreen-1.12.2-1.5.7.jar                           | None                                     |
       | LCHIJA | customspawner            | 3.11.4                       | CustomMobSpawner-3.11.4.jar                                    | None                                     |
       | LCHIJA | ptrmodellib              | 1.0.5                        | PTRLib-1.0.5.jar                                               | None                                     |
       | LCHIJA | props                    | 2.6.3.7                      | Decocraft-2.6.3.7_1.12.2.jar                                   | None                                     |
       | LCHIJA | doggytalents             | 1.15.1.5                     | DoggyTalents-1.12.2-1.15.1.5.jar                               | None                                     |
       | LCHIJA | mocreatures              | 12.0.5                       | DrZharks Mocreatures Mod-12.0.5.jar                            | None                                     |
       | LCHIJA | entityculling            | 6.0.2                        | EntityCulling-1.12.2-6.0.2.jar                                 | None                                     |
       | LCHIJA | epicfight                | 1.12.2-2.2.8                 | EpicFightMod-1.12.2-2.2.8.jar                                  | None                                     |
       | LCHIJA | falling_tree             | 2.4.0                        | FallingTree-1.12.2-2.4.0.jar                                   | None                                     |
       | LCHIJA | foamfix                  | 0.10.14-1.12.2               | foamfix-0.10.14-1.12.2.jar                                     | None                                     |
       | LCHIJA | forgelin                 | 1.8.4                        | Forgelin-1.8.4.jar                                             | None                                     |
       | LCHIJA | futuremc                 | 0.2.6                        | future-mc-0.2.10.jar                                           | None                                     |
       | LCHIJA | grapplemod               | 1.12.2-v12.3                 | grapplemod-1.12.2-v12.3.jar                                    | None                                     |
       | LCHIJA | hw_inv                   | 1.12.1-1.1.13                | hostileworlds_invasions-1.12.1-1.1.13.jar                      | None                                     |
       | LCHIJA | incontrol                | 3.9.18                       | incontrol-1.12-3.9.18.jar                                      | None                                     |
       | LCHIJA | jeiintegration           | 1.6.0                        | jeiintegration_1.12.2-1.6.0.jar                                | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.1                 | journeymap-1.12.2-5.7.1.jar                                    | None                                     |
       | LCHIJA | littletiles              | 1.5.0                        | LittleTiles_v1.5.58_mc1.12.2.jar                               | None                                     |
       | LCHIJA | spark                    | 1.5.2                        | spark-forge1122.jar                                            | None                                     |
       | LCHIJA | loliasm                  | 5.6                          | loliasm-5.6.jar                                                | None                                     |
       | LCHIJA | mcwdoors                 | 1.3                          | mcw-doors-1.0.3-mc1.12.2.jar                                   | None                                     |
       | LCHIJA | mcwfences                | 1.0.0                        | mcw-fences-1.0.0-mc1.12.2.jar                                  | None                                     |
       | LCHIJA | mcwfurnitures            | 1.0.1                        | mcw-furniture-1.0.1-mc1.12.2beta.jar                           | None                                     |
       | LCHIJA | mcwroofs                 | 1.0.1                        | mcw-roofs-1.0.1-mc1.12.2.jar                                   | None                                     |
       | LCHIJA | mcwtrpdoors              | 1.0.2                        | mcw-trapdoors-1.0.2-mc1.12.2.jar                               | None                                     |
       | LCHIJA | mcwwindows               | 1.0                          | mcw-windows-1.0.0-mc1.12.2.jar                                 | None                                     |
       | LCHIJA | millenaire               | Millénaire 8.1.2             | millenaire-8.1.2.jar                                           | None                                     |
       | LCHIJA | modnametooltip           | 1.10.1                       | modnametooltip_1.12.2-1.10.1.jar                               | None                                     |
       | LCHIJA | guilib                   | $version                     | morepaintings-paintings-1.12.2-5.0.1.2.jar                     | None                                     |
       | LCHIJA | paintingselgui           | $version                     | morepaintings-paintings-1.12.2-5.0.1.2.jar                     | None                                     |
       | LCHIJA | morepaintings            | $version                     | morepaintings-paintings-1.12.2-5.0.1.2.jar                     | None                                     |
       | LCHIJA | mousetweaks              | 2.10.1                       | MouseTweaks-2.10.1-mc1.12.2.jar                                | None                                     |
       | LCHIJA | llibrary                 | 1.7.20                       | llibrary-1.7.20-1.12.2.jar                                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs              | 1.5.8                        | mowziesmobs-1.5.8.jar                                          | None                                     |
       | LCHIJA | particleculling          | v1.3                         | particleculling-1.12.2-v1.3.1.jar                              | None                                     |
       | LCHIJA | performant               | 1.12.2-1.5                   | performant-1.11.jar                                            | None                                     |
       | LCHIJA | randomtweaks             | 1.12.2-2.8.3.1               | randomtweaks-1.12.2-2.8.3.1.jar                                | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCHIJA | renderlib                | 1.1.4                        | RenderLib-1.12.2-1.1.4.jar                                     | None                                     |
       | LCHIJA | roost                    | 2.0.10                       | roost-1.12.2-2.0.10.jar                                        | None                                     |
       | LCHIJA | sekcphysics              | 0.1.0                        | sekcphysics-0.1.0.jar                                          | None                                     |
       | LCHIJA | stupidthings             | 1.1.5                        | Stupid+Things-1.12.X-1.1.5.jar                                 | None                                     |
       | LCHIJA | torchslabmod             | v1.5.2                       | torchslabmod-1.12.2-v1.5.2.jar                                 | None                                     |
       | LCHIJA | wearablebackpacks        | 3.1.4                        | WearableBackpacks-1.12.2-3.1.4.jar                             | None                                     |
       | LCHIJA | worldedit                | 6.1.8                        | worldedit-forge-mc1.12-6.1.8-dist.jar                          | None                                     |
       | LCHIJA | worldeditcuife2          | 2.1.2-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12.2-14.23.5.2768.jar | None                                     |
       | LCHIJA | worldutils               | 0.4.2                        | worldutils-1.12.2-0.4.2.jar                                    | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | phosphor-lighting        | 1.12.2-0.2.7                 | phosphor-forge-mc1.12.2-0.2.7-universal.jar                    | None                                     |
       | LCHIJA | mysticallib              | 1.12.2-1.13.0                | mysticallib-1.12.2-1.13.0.jar                                  | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.5.7.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.7.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      LittlePatchingLoader (LittleTiles_v1.5.58_mc1.12.2.jar)
                                        com.creativemd.littletiles.LittleTilesTransformer
                                      MixinBooter (!mixinbooter-5.0.jar)
                                        
                                      LoliASM (loliasm-5.6.jar)
                                        
                                      EntityCullingPlugin (EntityCulling-1.12.2-6.0.2.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
                                      RenderLibPlugin (RenderLib-1.12.2-1.1.4.jar)
                                        meldexun.renderlib.asm.RenderLibClassTransformer
                                      FutureMC (future-mc-0.2.10.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      CustomSkinLoader (CustomSkinLoader_ForgeLegacy-14.14-SNAPSHOT-323.jar)
                                        customskinloader.forge.loader.LaunchWrapper
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.59' Renderer: 'NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: MultiMC5
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.59, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: millenaire-shields-128x128.zip, millenaire-hd-1.0.3.zip, Conquest+Reforged+RP.zip, Conquest_1.12 - Copie (2).zip
  Current Language: Français (France)
  Profiler Position: N/A (disabled)
  CPU: 24x AMD Ryzen 9 3900X 12-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

</details>

**Comment by koravel** [comment]
@G1ll0u @Rongmario Can confirm that. It happens when censoredasm works with Optifine.

Versions:
- Minecraft 1.12.2
- Forge 14.23.5.2860
- censoredasm5.12
- Optifine HD U G6_pre1

Tested with older versions of OF - same thing.

**Comment by Radplay** [comment]
Can confirm, happens both with and without OptiFine (Forge 14.23.5.2860, CensoredASM 5.14).

**Comment by Rongmario** [comment]
Pinned and changed title for visibility

**Comment by Rongmario** [comment]
[This is now being addressed in Nothirium directly.](https://github.com/Meldexun/Nothirium/pull/87)

**Comment by leonpano2006** [comment]
> [This is now being addressed in Nothirium directly.](https://github.com/Meldexun/Nothirium/pull/87)
希望這個問題可以趕快修好
因為把`onDemandAnimatedTextures`給停用掉之後 如果設定裡面的地形動畫是打開的話 我的Minecraft將會直接掉到1FPS
而且幾乎不怎麼浮動 然後我也沒有看到因為打開或者是關閉導致的CPU使用率上升或者是下降+顯示卡3D使用量
![image](https://github.com/LoliKingdom/LoliASM/assets/58368166/1cb53f46-abc7-433e-8315-c4714eaa6145)

然後我用了jmc flight recording
https://cdn.discordapp.com/attachments/760045284960239646/1168661613197402132/flight_recording_localhost7095.jfr?ex=655293f1&is=65401ef1&hm=59b711670d66bb616e7e2d912b80105cb669286da3bf5c5515f2799604e3d7a8&
