### ISSUE TITLE
Rendering issue with Simple Camp Fire mod

### ISSUE THREAD

**Issue by Ski-z** [LoliKingdom/LoliASM#132]
Mod: https://www.curseforge.com/minecraft/mc-mods/simple-camp-fire

### Without loliASM installed: 
![2022-08-18_18 29 22](https://user-images.githubusercontent.com/107653759/185518350-4dbe497c-e525-4864-bb70-4880a7c8c823.png)

No rendering issue on "cooking" and "finished cooked" items rendering.

### WITH loliASM installed:
![2022-08-18_18 40 03](https://user-images.githubusercontent.com/107653759/185518411-0c198a03-4f3b-4ad9-8719-b19596128c31.png)
![2022-08-18_18 40 16](https://user-images.githubusercontent.com/107653759/185518412-3cf37ca8-fb1f-4bfc-87d0-a6ffe525d6ad.png)
![2022-08-18_18 40 41](https://user-images.githubusercontent.com/107653759/185518413-43940309-2fc5-41cb-991b-9a8f9fcc9034.png)

Weird partial-rendering on the "cooking" and "finished cooked" items rendering. Is there a setting I need to change, or does there need to be a compat added?

**Comment by Rongmario** [comment]
Need a follow up.

**Comment by Ski-z** [comment]
disabling `squashBakedQuads` worked.
