### ISSUE TITLE
Chests/signs/doors corrupting themselves based on a specific area i look

### ISSUE THREAD

**Issue by catmality** [LoliKingdom/LoliASM#133]
![image](https://user-images.githubusercontent.com/112207464/186986163-36f7be7d-ba7f-4ab4-9494-da444425ee3f.png)
![image](https://user-images.githubusercontent.com/112207464/186986187-ad7e410c-524d-413a-b40c-7b8cfdd53681.png)
looking west/south does this. I know its this mod, but despite tinkering with some settings this still happens. the strange thing is that there are days/times this doesn't occur.
config: https://pastebin.com/AwBnmbe
latest log, if its help: [latest.log](https://github.com/LoliKingdom/LoliASM/files/9436272/latest.log)

it wouldnt surprise me if its some form of incompatibility with a different performance improving mod

**Comment by catmality** [comment]
This may be less of a mod issue and more of a hardware issue. after closing some tabs and programs to clear up some free RAM it doesn't happen.

**Comment by Rongmario** [comment]
I don't really touch rendering in LoliASM, but I'll leave this open for the time being.
