### ISSUE TITLE
Vanilla minecraft search failure

### ISSUE THREAD

**Issue by YUNGHOD** [LoliKingdom/LoliASM#135]
mc 1.12.2 ver 5.6
creative > press e  > search > nothing shows

**Comment by Rongmario** [comment]
Do you have JEI/HEI installed?

**Comment by JustDesoroxxx** [comment]
I had this issue before I cannot confirm that it is from LoliASM but it only happen without HEI/JEI I will test later

**Comment by JustDesoroxxx** [comment]
So after a test I can confirm that this happen only without HEI/JEI, and that the issue come from LoliASM

**Comment by YUNGHOD** [comment]
No i dont have JEI installed

**Comment by JustDesoroxxx** [comment]
Found out that the line below exist in the config so this is why, it is by default on and thus if JEI is not here the creative search is not working

```
    # If JEI/HEI is installed, replace vanilla search trees with JEI's, decreases memory usage, loading time and adds more features to normal creative menu searching - <default: true>
    B:replaceSearchTreeWithJEISearching=true
```
