### ISSUE TITLE
Crash after breaking Dynamic Trees log

### ISSUE THREAD

**Issue by AliceDTRH** [LoliKingdom/LoliASM#141]
https://mclo.gs/2o3ZCB2

After adding ``com.ferreusveritas.dynamictrees.render.RenderFallingTree.drawBakedQuad`` to ``S:classesThatCallBakedQuadCtor`` it stopped crashing for me. No clue if I just got lucky or anything but figured I'd let you guys know?

**Comment by MagmaBro123** [comment]
Doing this still gave a crash. This issue really needs fixing.

[debug.log](https://github.com/LoliKingdom/LoliASM/files/10680561/debug.log)

**Comment by Rongmario** [comment]
## v6 ain't out yet Magma
<img src="https://user-images.githubusercontent.com/3684700/217399125-e672f765-aad6-4837-8170-8b650d7b55bd.png" width="400" height="400">

**Comment by MagmaBro123** [comment]
The last commit was 5 months ago on the v6 branch, sooooo...

**Comment by Rongmario** [comment]
I'm not too sure Magma... maybe its because people like you deter me from working on this project
