### ISSUE TITLE
Documentation on how to use this with Spark

### ISSUE THREAD

**Issue by TheAirBlow** [LoliKingdom/LoliASM#143]
The config has a lot of options to profile game loading stages, world loading, etc. but it's not documented how to use this thing.
And for some reason most of them are disabled by default. Why?

**Comment by Rongmario** [comment]
1. Turn it on, and the links to the spark profiler results will show up in the log files.
2. They're disabled by default, so the game isn't profiled every time it loads. It'd allso be inconsiderate to the spark guys.

**Comment by TheAirBlow** [comment]
> 1. Turn it on, and the links to the spark profiler results will show up in the log files.
> 
>     2. They're disabled by default, so the game isn't profiled every time it loads. It'd allso be inconsiderate to the spark guys.

@Rongmario how to update Spark? It doesn't let me do it, LoliASM forces me to use `1.5.2`.
