### ISSUE TITLE
1.12.2 Out of memory in my pack when set to 8 GB

### ISSUE THREAD

**Issue by Kasia1403** [LoliKingdom/LoliASM#152]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/10310741/latest.log)

**Comment by Rongmario** [comment]
I don't know what `MinecraftFPSCode.jar` is but you should remove it. You also have TexFix which is incompatible with LoliASM.

With 716 mods (and some of them being extremely memory hungry) you definitely need more than 8GB RAM allocated, even with LoliASM.

**Comment by Kasia1403** [comment]
MinecraftFPSCode.jar - I found it somewhere, but I don't remember where and I thought it is something that will boost FPS. But do You think it may be fake and a virus ?

**Comment by Rongmario** [comment]
I'm not sure, I haven't heard of such a thing on 1.12.2.

**Comment by Kasia1403** [comment]
Could You read about it for me ?

**Comment by Kasia1403** [comment]
It is probably from here https://github.com/Lusin333/Minecraft-FPS-Hack/blob/master/MinecraftFPSCode.jar.txt

**Comment by Rongmario** [comment]
What the fuck am I looking at, remove it lmao

**Comment by Kasia1403** [comment]
But what is this ?

**Comment by Kasia1403** [comment]
I moved MinecraftFPSCode.jar to .minecraft folder.

**Comment by Kasia1403** [comment]
I removed VanillaFix and TexFix. Should I remove also Fast Furnace ?

**Comment by Kasia1403** [comment]
Now I decided to remove all mods uncompatible with LoliASM/CensoredASM and add LoliASM/CensoredASM and also the same with Universal Tweaks.

**Comment by Rongmario** [comment]
> I removed VanillaFix and TexFix. Should I remove also Fast Furnace ?

Yes
