### ISSUE TITLE
[1.12.2] [Client] Incompatibility with Thaumcraft6, unable to make vis crystals in the Thaumatorium when in a server without LoliASM.

### ISSUE THREAD

**Issue by Revelates** [LoliKingdom/LoliASM#154]
This only happens when connecting to a server **that doesn't have Loliasm**.

To replicate the problem right click a Thaumatorium, put in some quartz sliver and attempt to make a vis crystal (it refuses to show cost of making said vis crystal).

mods loaded are...

Forge 14.23.4.2860 Both client and server

-Loliasm-5.6 (On client, not on server)

-Thaumcraft-1.12.2-6.1.BETA26
-Baubles-1.12-1.5.2
-!mixinbooter-7.0

**Comment by Serega007RU** [comment]
Go to the mod configuration and disable the following parameters:
nbtTagStringBackingStringCanonicalization=false
nbtBackingMapStringCanonicalization=false
delayItemStackCapabilityInit=false
optimizeNBTTagCompoundBackingMap=false

This will help solve your problem.

Unfortunately, I don't remember exactly which of these parameters affects this problem, try disabling everything that I have listed.

**Comment by Rongmario** [comment]
Unfortunately Thaumcraft hashes ItemStacks with NBTTagCompound#toString, this may not be wholly fixed, as I'd have to patch it explicitly. But it is configurable at least. Closing for now.

**Comment by ireece1** [comment]
Sorry to bump a closed but i'm having the exact same issue; I can't create Vis Crystals in a Crucible, even with the 4 disabled parameters and even when in a singleplayer world.

I'm using CensoredASM 5.14

**Comment by Rongmario** [comment]
Turn off the configs @Serega007RU had mentioned, will be reviewed in version 6.
