### ISSUE TITLE
Is this mod dead? Last update/commit was 7 months ago.

### ISSUE THREAD

**Issue by MagmaBro123** [LoliKingdom/LoliASM#156]

**Comment by Rongmario** [comment]
You tell me

**Comment by AlexChevios** [comment]
What's happening? I can see recent upstream changes and commits at other projects, but here at v6 seems to be, if not dead, then packed in a freezer.

**Comment by Rongmario** [comment]
You're right. I freezed it, smashed it with a hammer for it to break into millions of unrecoverable pieces.
