### ISSUE TITLE
切换子服疯狂 弹报错

### ISSUE THREAD

**Issue by kang-png** [LoliKingdom/LoliASM#159]
crash：https://pastebin.pl/view/ef3fd910
每次切换子服都会疯狂报错。
去掉这个mod可以正常进去
希望可以通过调模组配置来解决
（优化效果非常好，不想删）

**Comment by kang-png** [comment]
> 這應該不是LoliASM導致的, 有`debug.log`嗎?

有呢 https://pastebin.pl/view/de609f3f
debug.log太大了 只能节选

**Comment by Rongmario** [comment]
移除autologin後試看看

**Comment by Rongmario** [comment]
如果再有問題，請重開issue
