### ISSUE TITLE
crash loop on loading a world with 5.7

### ISSUE THREAD

**Issue by unix-supremacist** [LoliKingdom/LoliASM#166]
os: arch linux
[log](https://github.com/LoliKingdom/LoliASM/files/11502238/a.txt)
jvm: openj9 java 8, but confirmed happens on openjdk8 as well

also it says out of memory error, but im running nothing but loliasm and gave the instance 1gb, this can't be correct

**Comment by Mysticpasta1** [comment]
you should add mixin booter and more RAM

**Comment by unix-supremacist** [comment]
mixinbooter is obviously in, its a dep, and theres no reason loliasm with no other mods should need more than 1gb of ram
