### ISSUE TITLE
Crash when breaking trees from DynamicTrees

### ISSUE THREAD

**Issue by SpeeeDCraft** [LoliKingdom/LoliASM#17]
Crash when Dynamic trees installed, and i breaking tree it

**Comment by Rongmario** [comment]
Crash report?

**Comment by SpeeeDCraft** [comment]
https://paste.dimdev.org/ihamodoruy.mccrash

**Comment by SpeeeDCraft** [comment]
And this happens if Optifine is not installed. If you install Optifine, there will be no crash.

**Comment by Rongmario** [comment]
@SpeeeDCraft disable `squashBakedQuads` in the config for now, I'll fix this in either 2.7 or 2.8

**Comment by SpeeeDCraft** [comment]
@Rongmario Thanks a lot :)

**Comment by Rongmario** [comment]
Ah seems like it was a config issue all along, insert

`com.ferreusveritas.dynamictrees.client.QuadManipulator`
and
`com.ferreusveritas.dynamictrees.models.bakedmodels.BakedModelBlockBranchCactus`

in `classesThatCallBakedQuadCtor` of the config, and it'll work fine.
