### ISSUE TITLE
Server crashed since v5.7 update

### ISSUE THREAD

**Issue by HaHaWTH** [LoliKingdom/LoliASM#174]
Server environment:
Minecraft Forge 14.23.5.2860
MixinBooter 8.2
Azul ZuluJDK 8u362 64bit, 
Oracle OpenJDK 8u351 64bit
Windows Server 2012 R2
My server kept being crashed since v5.7 update, now I could only use 5.6 version.:(
Logs,  Configs and Debugs with LoliASM v5.11 installed:
[Logs](https://paste.gg/p/anonymous/473abb79419e4fb094f62c2f71b9c675) [Configs](https://paste.gg/p/anonymous/ef93b80f1e0e45b1b9c97b1d9a4917e5) [Debugs](https://paste.gg/p/anonymous/83fb7c1782ef4f1381123d9c0db7c795)

**Comment by Rongmario** [comment]
Are you using CatServer?

**Comment by HaHaWTH** [comment]
> Are you using CatServer?

Ah, yes, the latest dev build. I haven‘t tested it on regular Forge server

**Comment by Rongmario** [comment]
There's an issue with CatServer at the moment, it may be fixed later I'm not sure.

**Comment by HaHaWTH** [comment]
Ah okay, thx❤, waiting for Luohuayu to fix it :), before the issue being resolved, only v5.6 and earlier versions can be used on CatServer, Sincerely hope it will be fixed🙏

**Comment by HaHaWTH** [comment]
Bug is Fixed!

**Comment by HaHaWTH** [comment]
Bug is Fixed!
