### ISSUE TITLE
CTD after update

### ISSUE THREAD

**Issue by festro** [LoliKingdom/LoliASM#179]
After the latest update (censoredasm5.13.jar) I'm getting a CTD.
Here's the log.
[crash-2023-06-12_11.25.05-client.txt](https://github.com/LoliKingdom/LoliASM/files/11726826/crash-2023-06-12_11.25.05-client.txt)

**Comment by Rongmario** [comment]
Can I see the full log? Should be something in there

**Comment by festro** [comment]
Thanks, been looking for a replacement for phosphorous, will try with that first, any chance you know of an alternative for better portals? it's a pretty big prat of my modpack.

**Comment by festro** [comment]
ok replaced the phosphor and disabled betterportals, not I get this

[crash-2023-06-12_11.57.13-client.txt](https://github.com/LoliKingdom/LoliASM/files/11727185/crash-2023-06-12_11.57.13-client.txt)


[latest.log](https://github.com/LoliKingdom/LoliASM/files/11727182/latest.log)

**Comment by Rongmario** [comment]
I don't think there's an alternative to Better Portals on 1.12.2 right now, and are you sure the crash is due to this mod and not something else?

**Comment by festro** [comment]
this was the only mod on my list to update recently and after checking the crashlog aside from better portals this mod was the only easy thing to spot which is why I came to the conclusion, but it is an older version minecraft so anything could have go wrong as I've had a modpack cause issues after not being played a while.

**Comment by festro** [comment]
Ok, turns out that JAOPCA is having an issue, rather than this mod. So basically after replacing Phosphor and disabling betterportals and JAOPCA the game starts now, thanks for the help.
