### ISSUE TITLE
New config report

### ISSUE THREAD

**Issue by magcicada** [LoliKingdom/LoliASM#18]
[IC2 and addons](https://www.curseforge.com/minecraft/mc-mods/industrial-craft):`[14:32:38] [Client thread/WARN]: class ic2.core.model.BasicBakedItemModel needs their BakedQuad calls redirecting! Insert the string into config/loliasm.json and report to Rongmario.`
[Double Slabs](https://www.curseforge.com/minecraft/mc-mods/double-slabs):`[14:52:52] [Client thread/WARN]: class cjminecraft.doubleslabs.client.model.VerticalSlabItemBakedModel needs their BakedQuad calls redirecting! Insert the string into config/loliasm.json and report to Rongmario.`

**Comment by magcicada** [comment]
IC2 and addons:`[21:54:54] [Client thread/WARN]: class ic2.core.model.MergedItemModel needs their BakedQuad calls redirecting! Insert the string into config/loliasm.json and report to Rongmario.`

**Comment by Rongmario** [comment]
=> https://github.com/LoliKingdom/LoliASM/issues/14
