### ISSUE TITLE
服务端加载mod时崩溃

### ISSUE THREAD

**Issue by koeret** [LoliKingdom/LoliASM#181]
服务端仅加载了LoliASM5.13，minibooter-8.2，服务端核心为Catserver，Minecraft版本1.12.2，forge版本为14.23.5.2860 
,
[2023-06-15-7.log](https://github.com/LoliKingdom/LoliASM/files/11753597/2023-06-15-7.log)

**Comment by koeret** [comment]
在客户端运行5.13版本的时候不会导致崩溃，服务端加载5.6版本时同样能正常运行。

**Comment by Lonelyxiya** [comment]
mixinbooter建议用7.1以下版本

**Comment by koerdoe** [comment]
mixinbooter使用8.3版本后问题解决

**Comment by koeret** [comment]
换用mixinbooter8.3之后不再崩溃了。
