### ISSUE TITLE
Catching Error from EndIO that doesn't exist causes crash on Start-Up

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [LoliKingdom/LoliASM#196]
Crash on start-up during pre-initialization stage;
Found a similar error on enderIO's bug report page that was closed, as a non-issue. Crash is caused by LoliASM, see attached log and debug.log as well:
[latest.log](https://github.com/LoliKingdom/LoliASM/files/12255939/latest.log)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/12255940/debug.log)
crash report here if a needed outside of the log:
[crash-2023-08-01_20.19.02-client.txt](https://github.com/LoliKingdom/LoliASM/files/12255956/crash-2023-08-01_20.19.02-client.txt)

**Comment by KorewaLidesu** [comment]
Remove TexFix and try again

**Comment by caniplzjustlogin4godsakesthistakesforev** [comment]
That fixed it, Thanks, marking as closed
