### ISSUE TITLE
Possible Incompatibly With CensoredASM 

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [LoliKingdom/LoliASM#198]
Game crashes after a few minutes of being in a world. Log mentions CensoredASM but idk what is causing this.

[crash-2023-08-08_14.44.26-server.txt](https://github.com/LoliKingdom/LoliASM/files/12295478/crash-2023-08-08_14.44.26-server.txt)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/12295482/latest.log)

**Comment by LegendaryCrystalFox** [comment]
seems it might of been another mod my bad-

**Comment by mattrix444** [comment]
what mod was by chance? im getting super lag with loli and censored but they are mentioned in the logs but other stuff is also

**Comment by Airisii** [comment]
I believe my crashes were from a mod called Mappet. It has nothing to do with censoredASM, it just mentions it in the log.
