### ISSUE TITLE
Crash with MysticalLib

### ISSUE THREAD

**Issue by Verph** [LoliKingdom/LoliASM#2]
Hi,

The game crashes if you launch the game with MysticalLib the second time and onwards. 

MysticalLib version 1.10.0. Link: https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/3243257
LoliASM version 2.0.

[crash-2021-05-03_17.49.12-client.txt](https://github.com/LoliKingdom/LoliASM/files/6415961/crash-2021-05-03_17.49.12-client.txt)

**Comment by Rongmario** [comment]
On first glance it seems like MysticalLib is doing something absolutely unnecessary and is an edge-case so I have to take care of it. 

For now, wait for the 2.0.1 build to drop on CurseForge and turn off `bakedQuadsSquasher` in the config and it'll run.

**Comment by Sunconure11** [comment]
What's the status of this? I noticed this issue as well and was about to report it when I saw a crash report already filed.

**Comment by Rongmario** [comment]
Disable `bakedQuadsSquasher` for now. The only way to fix would be to hack MysticalLib's hack, which I'll investigate this weekend.

**Comment by Rongmario** [comment]
Fixes. When 2.5 comes out it will no longer crash.
