### ISSUE TITLE
Thaumcraft Incompatibility

### ISSUE THREAD

**Issue by SaltSouls** [LoliKingdom/LoliASM#20]
Doesn't work well with Thaumcraft's crystal blocks as it causes all different variants to render as just one color.
The instant this mod is disabled, they all go back to rendering the correct colors. Not sure what the cause of this is, but it's definitely a hindrance.

**Comment by Rongmario** [comment]
Add `thaumcraft.client.lib.obj.MeshModel` to `classesThatCallBakedQuadCtor` in `loliasm.cfg`.
