### ISSUE TITLE
Support Spark Unforged

### ISSUE THREAD

**Issue by mczph** [LoliKingdom/LoliASM#201]
https://www.curseforge.com/minecraft/mc-mods/spark-unforged/files

![image](https://github.com/LoliKingdom/LoliASM/assets/103164772/f8914505-01a3-4cd9-be2c-c4721d981d2b)

**Comment by xXDarkNovaXx** [comment]
I have read that only 1.5.2 was specified as compatible from the original Mod the latest Version (1.6.3 I think) should have been broken somehow

But if this Backport from Spark that backports newer Patches from newer Spark Version to 1.12.2 should work well I think a compatibility would not be bad
It can never hurt to keep a Mod up to date

**Comment by Rongmario** [comment]
Wait for [Flare](https://github.com/CleanroomMC/Flare).
