### ISSUE TITLE
New Rendering Bug

### ISSUE THREAD

**Issue by Hydraheads** [LoliKingdom/LoliASM#203]
When I updated the mod to 5.14, I have experienced (as well as someone else on my server) a bug where very rarely an entity will just freeze in place visually. They technically continue to move and act but they are visually frozen in place entirely.

We experienced this with customnpcs regularly summoned, where new instances of the same npc type wouldn't even render. and upon **changing their skins** from one texture location to another, they started to render properly. This leads me to believe the issue is tied to a change regarding... texture rendering?

I believe censoredasm is causing it because it was the only mod I updated between this issue happening, and after rolling it back to 5.1.3 we have not experienced the problem again.

**Comment by Rongmario** [comment]
Do you have both server/client logs for when this is happening?

**Comment by Hydraheads** [comment]
I do not have the logs sadly, as I do not know the date and times of the occasions and there were many many sessions within the last couple of weeks. But I can confirm it happened in a singleplayer world in addition to the server.

**Comment by Rongmario** [comment]
If you do come across it, please do send logs over. Can I have the mod list first nonetheless?

**Comment by Rongmario** [comment]
Please reopen if you can reproduce this consistently with relevant log.
