### ISSUE TITLE
incompatibility with nothirium

### ISSUE THREAD

**Issue by Moonyol** [LoliKingdom/LoliASM#207]
![image](https://github.com/LoliKingdom/LoliASM/assets/92951072/cb5a747d-184c-4778-bcf8-aac31b55f18a)

https://github.com/LoliKingdom/LoliASM/assets/92951072/2c67af89-5325-47d7-be24-97f7c60facb0

**Comment by Moonyol** [comment]
i dont have optifine tho

**Comment by KorewaLidesu** [comment]
Check for the config change...

**Comment by Rongmario** [comment]
Disable `onDemandAnimatedTextures`, I won't try to be compatible with Nothirium because of its ARR nature.

**Comment by Moonyol** [comment]
wdym by arr
