### ISSUE TITLE
3 way incompatibility with tough as nails and weather2 remastered

### ISSUE THREAD

**Issue by Moonyol** [LoliKingdom/LoliASM#208]
screen goes orange when the heat icon is fire, normally it would tint it slightly orange
![image](https://github.com/LoliKingdom/LoliASM/assets/92951072/f18c7017-3a1d-4c7f-8e5a-1d54e9859877)

what happens: ![image](https://github.com/LoliKingdom/LoliASM/assets/92951072/96cf702a-2cce-4f2e-a26d-feedcc93d9c0)
expected: ![image](https://github.com/LoliKingdom/LoliASM/assets/92951072/afeae44a-1169-4fe9-8b5f-745ad0a73f3d)

**Comment by Rongmario** [comment]
Can you post your log files for when this occurs?

**Comment by Moonyol** [comment]
it doesnt show anything when it happens and im probably missing something because now it worked broke again and works again

**Comment by Rongmario** [comment]
Feel free to reopen if you can reproduce consistently, or if anyone else is experiencing the same thing.

**Comment by Moonyol** [comment]
it can also happen with the freezing effect
