### ISSUE TITLE
Some weird bug Regarding Horsepower Mod 

### ISSUE THREAD

**Issue by Cinamonfire** [LoliKingdom/LoliASM#212]
Ok so whenever I install CensoredASM and i attempt to use the hand grindstone or horse powered one or any other block from that mod? i right click it, and the blocks static and doesnt even operate, what could be the cause of this bug? and what config options should i set in order to enable said blocks, because this bug might effect other modded blocks and i dont want that happening in the modpack im developing...

[latest.log](https://github.com/LoliKingdom/LoliASM/files/12708932/latest.log)

**Comment by ISurrealI** [comment]
Please post the mod list because i couldn't recreate it with censoredasm or vintagefix. Also if you tried it without any input try to put an input such as wheat and try right clicking again.

**Comment by Cinamonfire** [comment]
Heres the Mods list:
minecraft - Minecraft - 1.12.2
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.5.2855
agriseasons - AgriSeasons - 1.0.2
mixinbooter - MixinBooter - 8.6
com.elytradev.movingworld.common.asm.coremod - MovingWorld CORE - 
bnbgamingcore - BnBGamingCore - 0.12.0
foamfixcore - FoamFixCore - 7.7.4
infinitylib - InfinityLib - 1.12.2-1.12.1
agricraft - AgriCraft - 2.12.0-1.12.2-b2
aireducer - AI Reducer - 0.3.0
amidst-forge - Amidst Bridge mod - 1.12.2-0.6.2
codechickenlib - CodeChicken Lib - 3.2.3.358
ancientwarfare - Ancient Warfare Core - 1.12.2-2.7.0.1038
ancientwarfareautomation - Ancient Warfare Automation - 1.12.2-2.7.0.1038
ancientwarfarenpc - Ancient Warfare NPCs - 1.12.2-2.7.0.1038
ancientwarfarestructure - Ancient Warfare Structures - 1.12.2-2.7.0.1038
ancientwarfarevehicle - Ancient Warfare Vehicles - 1.12.2-2.7.0.1038
biomesoplenty - Biomes O' Plenty - 7.0.1.2444
baubles - Baubles - 1.5.2
crafttweaker - CraftTweaker2 - 4.1.20
jei - Just Enough Items - 4.16.1.301
botania - Botania - r1.10-364
craftstudioapi - CraftStudio API - 1.0.0
harvestcraft - Pam's HarvestCraft - 1.12.2zb
animania - Animania - 2.0.3.28
applecore - AppleCore - 3.4.0
aquaacrobatics - Aqua Acrobatics - 1.15.3
aquaculture - Aquaculture - 1.6.8
armourers_workshop - Armourer's Workshop - 1.12.2-0.51.0
artemislib - ArtemisLib - 1.0.6
astikorcarts - AstikorCarts - 1.12.2-0.1.2.8
quark - Quark - r1.6-179
autoreglib - AutoRegLib - 1.3-32
B3M - Вращение Земли Майнкрафтская - 1.12.2-17
bedbreakbegone - BedBreakBegone - 1.0.2
betteradvancements - Better Advancements - 0.1.0.77
bettercaves - YUNG's Better Caves - 1.12.2
bettermineshafts - YUNG's Better Mineshafts - 1.12.2-2.2.1
bibliocraft - BiblioCraft - 2.4.6
birdsnests - Bird's nests - 2.1.0
blockcraftery - Blockcraftery - 1.12.2-1.3.1
bnbgaminglib - BNBGamingLib - 2.17.6
bookshelf - Bookshelf - 2.3.590
bountifulbaubles - Bountiful Baubles - 0.0.1
forgelin - Shadowfacts' Forgelin - 1.8.4
bountiful - Bountiful - 2.2.2
camels - Camels Mod - 1.0.1
carrots - Carrots Lib - 1.0.0b1
ctm - CTM - MC1.12.2-1.0.2.31
chisel - Chisel - MC1.12.2-1.0.2.45
cathedral - Cathedral - 1.12.2-1.9.9
loliasm - LoliASM - 5.15
sandro - Sandro's Core - 1.3d
redstoneplusplus - Redstone++ - 1.3e
charm - Charm - 1.4
clienttweaks - Client Tweaks - 3.1.11
collective - Collective - 3.0
fantasticlib - Fantastic Lib - 1.12.2.047
controlledburn - Controlled Burn - 1.12.2.022
controlling - Controlling - 3.0.10
corpse - Corpse - 1.12.2-1.0.8
craftpresence - CraftPresence - 2.2.3
ctgui - CT-GUI - 1.0.0
crafttweakerjei - CraftTweaker JEI Support - 2.0.3
creaturebeacons - Creatures Love Beacons - 1.12.2-1.0.1
custombackgrounds - Custom Backgrounds - 1.0
customloadingscreen - Custom Loading Screen - 1.12.2-1.5.7
custommainmenu - Custom Main Menu - 2.0.9.1
customnpcs - CustomNPCs - 1.12
movingworld - Moving World - 1.12-6.353
davincisvessels - Davinci's Vessels - @DVESSELSVER@
dawnoftimebuilder - Dawn Of Time : Builder Edition - 1.0.7
earthworks - Earthworks - 1.3.4.3
ebwizardry - Electroblob's Wizardry - 4.3.11
embers - Embers Rekindled - 1.19
enchcontrol - Enchantments Control - 1.1.5
fastleafdecay - Fast Leaf Decay - v14
fastbench - FastWorkbench - 1.7.4
fluidlogged_api - Fluidlogged API - 2.2.4
foamfix - FoamFix - @VERSION@
foamflower - Foamflower - 1.12.2-1.0.0.0-beta1
ftblib - FTB Library - 5.4.7.2
ftbutilities - FTB Utilities - 5.4.1.131
geographicraft - GeographiCraft - 0.8.7
rustic - Rustic - 1.1.7
growthcraft - Growthcraft - 4.2.2
growthcraft_fishtrap - Growthcraft Fishtrap - 4.2.2
growthcraft_apples - Growthcraft Apples - 4.2.2
growthcraft_cellar - Growthcraft Cellar - 4.2.2
growthcraft_grapes - Growthcraft Grapes - 4.2.2
growthcraft_bamboo - Growthcraft Bamboo - 4.2.2
growthcraft_bees - Growthcraft Bees - 4.2.2
growthcraft_rice - Growthcraft Rice - 4.2.2
growthcraft_hops - Growthcraft Hops - 4.2.2
growthcraft_milk - Growthcraft Milk - 4.2.2
horse_tack - Horse Tack - 4.0.0
wasaila - What Agricraft Stats Am I Looking At - 1.0
waila - Waila - 1.8.26
horsepower - Horse Power - 2.6.4
llibrary - LLibrary - 1.7.20
iceandfire - Ice and Fire - 1.9.1
iguanatweaks - IguanaTweaks Reborn - 1.5.1
inventorytweaks - Inventory Tweaks - 1.63+release.109.220f184
itemzoom - Item Zoom - 1.11
itlt - It's the little things - 1.0.4
jjcoa - JJ Coats of Arms - 1.0.11
journeymap - JourneyMap - 1.12.2-5.7.1
librarianlib - LibrarianLib - 4.22
lieutenant - Lieutenant - 1.4
locks - Locks - 3.0.0
loottweaker - LootTweaker - 0.3.1
lunatriuscore - LunatriusCore - 1.2.0.42
lycanitesmobs - Lycanites Mobs - 2.0.8.9 - MC 1.12.2
reborncore - Reborn Core - 3.19.5
mainmenuscale - Main Menu Scale - 1.0
malisiscore - MalisisCore - 1.12.2-6.5.1-SNAPSHOT
malisisdoors - MalisisDoors - 1.12.2-7.3.0
mana_wizardry - Mana Wizardry - 0.3
minetraps - MineTraps - 1.0.4
mtrm - MineTweakerRecipeMaker - 1.2.2.30
mousetweaks - Mouse Tweaks - 2.10
mowziesmobs - Mowzie's Mobs - 1.5.8
naturalpledge - Natural Pledge - 3.0.3
netherportalfix - NetherPortalFix - 5.3.17
nomoreglowingpots - NoMoreGlowingPots - 1.2
neid - NotEnoughIDs - 1.5.4.4
oauth - OAuth - 1.06.4
oldguns - Old Guns Mod - 1.12.2-2.0.5
oreveins - Ore Veins - 2.0.15
pamsbreadcraft - Pam's BreadCraft - 1.1.0
particleculling - Particle Culling - v1.4.1
patchouli - Patchouli - 1.0-23.6
performant - performant Mod - 1.12.2-1.5
pirates - Pirates Mod - 0.0.6
placebo - Placebo - 1.6.0
plants2 - Plants - 2.10.7
redstonepaste - Redstone Paste - 1.7.5
resourceloader - Resource Loader - 1.5.3
rusticbopwoods - Rustic BOP Woods - 1.0
schematica - Schematica - 1.8.0.169
sereneseasons - Serene Seasons - 1.2.18
serenetweaks - Serene Tweaks - 0.0.1
shipwrecks_winslow - Shipwrecks! - 2.0.0
soot - Soot - 1.10-hotfix
soundfilters - Sound Filters - 0.12.1_for_1.12
stg - SwingThroughGrass - 1.12.2-1.2.3
superhostiletokens - Super Hostile Tokens - 1.0.0
surge - Surge - 2.0.77
tammodized - TamModized - 0.15.6
teastory - TeaStory - 3.3.3-B33.418-1.12.2
tellme - Tell Me - 0.7.0-dev.20200919.184303
tidychunk - TidyChunk - 1.0.0.0
trade - Trade - 1.0.4
trapcraft - Trapcraft - 2.4.5
xat - Trinkets and Baubles - 0.32
triumph - Triumph - 3.19.2
uteamcore - U Team Core - 2.2.5.255
unlimitedchiselworks - Unlimited Chisel Works - 0.3.5
unridekeybind - UnRide Keybind - 1.0
vending - Vending - 1.12.2-3.0.1.2
venomousfangs - Venomous Fangs - 1.1
wawla - What Are We Looking At - 2.6.275
waystones - Waystones - 4.1.0
worldborder - World Border - 2.3
worldedit - WorldEdit - 6.1.10
xpbook - XP Tome - v2.0.1
xray - XRay - 2.0.0
recipehandler - Yet Another Recipe Conflict Fixer - 0.14
ancientspellcraft - AncientSpellcraft - 1.12.2-1.5.10
betteranimalsplus - Better Animals Plus - 9.0.1
minefantasyreforged - MineFantasy Reforged - 1.12.2-0.2.9
wizardryutils - WizardryUtils - 1.12.2-1.1.4
mospells - mospells - 1.12.2-1.0.4
phosphor-lighting - Hesperus, fork from Phosphor - 1.12.2-0.2.9.3
rtg - Realistic Terrain Generation - 6.1.0.0-snapshot.1
solcarrot - Spice of Life: Carrot Edition - 1.8.4
hungeroverhaul - Hunger Overhaul - 1.12.2-1.3.3.jenkins148
librarianliblate - LibrarianLib Stage 2 - 4.22
mysticallib - Mystical Lib - 1.12.2-1.13.0

**Comment by ISurrealI** [comment]
[Locks](https://www.curseforge.com/minecraft/mc-mods/locks) is the problem. I guess it works really bad in 1.12.2

**Comment by Cinamonfire** [comment]
Ill be running some tests regarding horsepower versions, if locks is the main issue then me and modpack dev team will have to make critical decisions

**Comment by Rongmario** [comment]
Do you have the pack downloadable anywhere so I can test it?

**Comment by Cinamonfire** [comment]
thats going to be problematic because the packs still in development and the test builds are strictly available only for pack testers, you can add me on discord and consult with the packs owner regarding if you can simply test the pack or join the test server for any kind of interest in it. [https://discord.gg/HNaAufyr](url)

**Comment by Rongmario** [comment]
Unfortunate, it'll probably take a while before I can properly diagnose it then...

**Comment by Cinamonfire** [comment]
nah you just gotta consult with the modpack owner and he approves , you just need to delete the test pack after you find a diagnosis for the issue

**Comment by Rongmario** [comment]
Disabling `optimizeNBTTagCompoundBackingMap` works for this scenario.
