### ISSUE TITLE
1.12.2 incompatibility with SpongeForge

### ISSUE THREAD

**Issue by cajlo** [LoliKingdom/LoliASM#216]
incompatibility with SpongeForge
tested censoredasm5.14/5.16 with : spongeforge-1.12.2-2838-7.4.8-RC4142.jar ; spongeforge-1.12.2-2838-7.4.7.jar
mixins conflict, rename not helping

**Comment by Rongmario** [comment]
Use 7.4.8, and the latest MixinBooter. And also turn off threadPriorityFix in the config.
