### ISSUE TITLE
[suggest] Switch to Spark Unforged

### ISSUE THREAD

**Issue by SrRapero720** [LoliKingdom/LoliASM#220]
Someone make a backport of latest Versions of spark for 1.12.2.
And looks pretty good, the problem is It cannot be uses with loliASM because It keeps same modID and version missmatch

**Comment by WolfBV** [comment]
https://github.com/LoliKingdom/LoliASM/issues/201

**Comment by Rongmario** [comment]
Correct. I won't keep you waiting much longer!

**Comment by ChromaPIE** [comment]
come on broo breh bruh
