### ISSUE TITLE
Thermal Expansion Satchel | Picking up items causes crash

### ISSUE THREAD

**Issue by Nitaeram** [LoliKingdom/LoliASM#221]
censoredasm5.18.jar

When picking up items game crashes. Don't know why and don't know what to change, it might be TE's fault.

Log: https://mclo.gs/ERhcrMJ

**Comment by Rongmario** [comment]
Remove dupefixproject and install [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks)

**Comment by Nitaeram** [comment]
thanks
