### ISSUE TITLE
Crash Involving EnderIO

### ISSUE THREAD

**Issue by RConTRS** [LoliKingdom/LoliASM#222]
i made a modpack with 300 mods, many performance mods works well but loliasm crashes the game
![image](https://github.com/LoliKingdom/LoliASM/assets/97401001/de8ede51-839f-42ed-a715-2a8b4a6ad42b)
also this is universaltweaks which has features of mods like vanillafix, however i tried removing it but the same issue still present
here's my crashlog [crash-2023-10-25_06.53.48-client.txt](https://github.com/LoliKingdom/LoliASM/files/13161182/crash-2023-10-25_06.53.48-client.txt)
in all cases loliasm appears to be in errored state (LCE)

**Comment by Rongmario** [comment]
Need the full log, doesn't look to be loliasm issue from the crash.

**Comment by RConTRS** [comment]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/13167603/latest.log)

**Comment by Rongmario** [comment]
Remove TexFix, its functionality is included and improved upon in loliasm.

**Comment by RConTRS** [comment]
thx it worked, i don't even know how texfix was there in the first place lol, closing the issue
