### ISSUE TITLE
lots of textures missing when this is installed

### ISSUE THREAD

**Issue by xemnes** [LoliKingdom/LoliASM#23]
hello, having an issue with missing textures from other mods when this mod is installed
ive looked through every item in my modpack, i think ive narrowed it down to projectred (and its addon modules) and draconic evolution 
heres some images:
https://i.imgur.com/pkYp2Qr.png
https://i.imgur.com/qJpqxls.png

its odd that its happening to only certain items and not others

edit: found out all tconstruct textures are completely white also
https://i.imgur.com/Zkw0tKZ.png

**Comment by Rongmario** [comment]
Disable `releaseSpriteFramesCache` in the config for now.

**Comment by xemnes** [comment]
thank you, will test. also as i didnt actually test, turns out blocks in the world are also missing textures 
![image](https://user-images.githubusercontent.com/603338/132967819-20271037-f9c6-4b36-8fb5-37d397ec325c.png)

will test this fix though to see if this also fixes this.

**Comment by Rongmario** [comment]
Yeah they use custom sprite loaders, I'll explicitly deal with this in v3.1.

**Comment by xemnes** [comment]
righto, good to know! if i find any more mods like this, should i report them? not sure if this problem needs a fix on a per mod basis

**Comment by xemnes** [comment]
huh, seems setting releaseSpriteFramesCache to false didnt do anything :/
the textures and item textures are still missing.

**Comment by Rongmario** [comment]
I'll take a look, feel free to revert to the previous version. Anything in the logs?

**Comment by xemnes** [comment]
not really sure what i should be looking for in the logs, heres my log if you want to take a look
[latest.log](https://github.com/LoliKingdom/LoliASM/files/7148889/latest.log)

**Comment by xemnes** [comment]
update on this, did some investigation and looked through the problem blockstate files for these items, every problem item is using `"transform": "ccl:default-item"` rather than `"transform": "forge:default-item"`
so i reckon this might be the culprit

**Comment by Rongmario** [comment]
Kek I know the problem now

**Comment by Rongmario** [comment]
Fixed in https://github.com/LoliKingdom/LoliASM/commit/ac6633618776d508cdbc17cbe9af3228221a268a - version 3.0.2

**Comment by xemnes** [comment]
thank you!
