### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jannikd3x** [LoliKingdom/LoliASM#232]
Log:
https://drive.google.com/file/d/1QkN_7dNr3nEiJoF-40mRKLKvxdJ1j4qO/view?usp=sharing

**Comment by brisingraerowing** [comment]
I'm getting this as well. I suspect [this class](https://github.com/LoliKingdom/LoliASM/blob/master/src/main/java/zone/rong/loliasm/common/java/JavaFixes.java) being at fault here.

**Comment by Rongmario** [comment]
Does look very weird, I'll note this as invalid until you found the cause.

**Comment by brisingraerowing** [comment]
I've isolated the cause as LittleFrames. Removing it allows loading the world. I'll report this to the dev there. I suspect the Watermedia library it uses is actually at fault.

**Comment by SrRapero720** [comment]
@Rongmario I still can't figure out why it still crashes and I have no clue :(

Maybe I had to sign Jar too?

**Comment by Rongmario** [comment]
Signing jars is optional unless you've provided an overriding classloader that somehow demands the jars to be signed.
