### ISSUE TITLE
Liteloader crash

### ISSUE THREAD

**Issue by erialsan** [LoliKingdom/LoliASM#234]
CRASHED by Liteloader.
Mod used is Liteloader (latest version)
CensoredASM (latest version)
forge14.23.5.2860
only

**Comment by Rongmario** [comment]
MixinBooter (which what loliasm relies on) is incompatible with liteloader.

**Comment by Strykus** [comment]
MixinBooter Works fine with LiteLoader/CensoredASM when mods used separately. Problem occurs when LiteLoader and CensoredASM used together (forge 14.23.5.2859)

**Comment by HowardZHY** [comment]
Set ```B:optimizeRegistries=false``` in ```datastructures``` of loliasm config.

> MixinBooter Works fine with LiteLoader/CensoredASM when mods used separately. Problem occurs when LiteLoader and CensoredASM used together (forge 14.23.5.2859)
