### ISSUE TITLE
releaseSpriteFramesCache causes lag spikes when opening inventory

### ISSUE THREAD

**Issue by ProTriforcer** [LoliKingdom/LoliASM#239]
Steps to reproduce:
1. get a pack with HEI, loliASM, GTCEu and their dependencies (i took nomi ceu nigtly and disabled every other mod for this test)
2. open loliasm.cfg and make sure releaseSpriteFramesCache is true (it probably is)
3. make a world
4. fill your bookmarks with items that have textures that take a while to generate like fluids and buckets
5. ALT+F3
6. open the inventory and see a lag spike
7. close the inventory and wait a second or two
8. open the inventory and see a lag spike
https://spark.lucko.me/JgJm59XOBs
![2024-02-16_05 22 03](https://github.com/LoliKingdom/LoliASM/assets/25221392/f85d2543-5c27-4d92-8626-c462dd4cf169)
9. set releaseSpriteFramesCache to false and restart
10. join a world and repeat 5-7
11. open the inventory and see no lag spike
![2024-02-16_05 24 42](https://github.com/LoliKingdom/LoliASM/assets/25221392/dceb28a7-3807-4984-927d-3f3bbe369ba0)

Logs:
[logs.zip](https://github.com/LoliKingdom/LoliASM/files/14304103/logs.zip)

**Comment by Rongmario** [comment]
This was broken in this commit: https://github.com/LoliKingdom/LoliASM/commit/8b423982e45039d9cc51ffa7ce2114d054d5dd18, will be fixed.
