### ISSUE TITLE
Tinkers rendering

### ISSUE THREAD

**Issue by Aeron216** [LoliKingdom/LoliASM#24]
3.0.3 

I have noticed problems with the rendering of casts and inventory icons. Similar to TexFix.

![2021-09-17_01 16 19](https://user-images.githubusercontent.com/54506307/133738838-c09495c7-ac57-41a3-b24b-08324f69c280.png)
![2021-09-17_01 16 20](https://user-images.githubusercontent.com/54506307/133738847-e4a8f187-2b99-485d-860d-3a2c076558b2.png)
![2021-09-17_01 16 22](https://user-images.githubusercontent.com/54506307/133739047-c783c1fd-0585-4132-84ed-139335437310.png)

![2021-09-17_01 33 04](https://user-images.githubusercontent.com/54506307/133738886-c68136aa-0461-4108-a96d-494b8b19a2d4.png)

![2021-09-17_01 57 32](https://user-images.githubusercontent.com/54506307/133738895-910caba8-abca-48a8-b19a-104345ca7685.png)

**Comment by Rongmario** [comment]
Disable `releaseSpriteFramesCache` for now, it'll be fixed in the upcoming release.

**Comment by Aeron216** [comment]
Will do, thanks.

**Comment by Rongmario** [comment]
@Aeron216 [Build](https://www.curseforge.com/minecraft/mc-mods/sneedasm/files/3475244) is up.
