### ISSUE TITLE
Bro just feels like spamming smth while the game's loading

### ISSUE THREAD

**Issue by ChromaPIE** [LoliKingdom/LoliASM#240]
Happens on 4/7, nonstop till force shutting the game manually

```
[11:23:21] [Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[11:23:21] [Client thread/ERROR] [minecraft/Minecraft]: @ LoliASM GUI Loop
[11:23:21] [Client thread/ERROR] [minecraft/Minecraft]: 1282: Invalid operation
```

Is it even related to this mod?
Using the 5.18 version
Using Azul Zulu Java 21
Using [this latest build](https://github.com/CleanroomMC/CleanroomMMC/actions/runs/7951535219) of Cleanroom
More info in the [full log](https://mclo.gs/9cjwq9b)

Did updated some mods after the last successful launch, let me know if you need a list.

**Comment by Rongmario** [comment]
This happens due to an old VanillaFix bug, it is fixed in v6. Though, you've crashed at [Line 8428](https://mclo.gs/9cjwq9b#L8428) hence why it is in an illegal state.

**Comment by ChromaPIE** [comment]
any workaround or snapshot of v6?

**Comment by Rongmario** [comment]
Resolve the crash and the bug will be gone.

**Comment by ChromaPIE** [comment]
oh aight it's on embers' side. i'll make a feedback

**Comment by ChromaPIE** [comment]
Solved on embers' side
