### ISSUE TITLE
Animated textures animate only when you typing something in HEI search bar

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/LoliASM#241]
This issue happen after updating to new LoliASM version.

https://github.com/LoliKingdom/LoliASM/assets/936618/dc8fe178-f172-45ff-a2fa-91153f2f037b

[loliasm.cfg](https://github.com/LoliKingdom/LoliASM/files/14359417/loliasm.log)

[debug.log](https://github.com/LoliKingdom/LoliASM/files/14359420/debug.log)

**Comment by Rongmario** [comment]
is HEI's ingredient buffer on?

**Comment by Krutoy242** [comment]
`B:bufferIngredientRenders=true` This option set to true

**Comment by Rongmario** [comment]
Try turning it off, does this bug still happen?

**Comment by Krutoy242** [comment]
I will test. Should i create issue on HEI then? Or this is intended behaviour? Its just happen when i updated LoliASM.

**Comment by Rongmario** [comment]
It happens because loliasm was broken and didn't work as intended.

**Comment by Rongmario** [comment]
Fixed 2 versions back, forgot to close.
