### ISSUE TITLE
Crashed in dev environment, NoSuchMethodError

### ISSUE THREAD

**Issue by Vetpetmon** [LoliKingdom/LoliASM#242]
[crash-2024-02-26_17.09.56-client.txt](https://github.com/LoliKingdom/LoliASM/files/14411907/crash-2024-02-26_17.09.56-client.txt)

In the dev environment of Wyrms of Nyrus, using no debug flags with Gradle Wrapper 8.5 and RFG 1.3.28.

**Comment by Rongmario** [comment]
Deobfuscate the mod first, otherwise it won't work.
