### ISSUE TITLE
Missing fix from censoredASM for Subaquatic textures

### ISSUE THREAD

**Issue by Mindr0ide** [LoliKingdom/LoliASM#244]
there is a bug in Subaquatic that removes water and other subaquatic item textures, and normally, with censoredASM downloaded it fixes this issue. However when i replaced censoredASM with NormalASM the issue came back.

**Comment by Mindr0ide** [comment]
![image](https://github.com/LoliKingdom/LoliASM/assets/142521261/93cb3b5b-9394-4fb0-9253-6ea2af391001)

**Comment by Rongmario** [comment]
Do not use NormalASM or its derivatives, they're outdated and buggy.
