### ISSUE TITLE
Foamfix suspicions

### ISSUE THREAD

**Issue by Aeron216** [LoliKingdom/LoliASM#25]
I have my suspicions that foamfix is having an incompatibility thing going on here since I saw its name mentioned. 

My bad if Im wrong.

Happens short after someone enters the Nether while on my server, a couple of steps in. Never happened during Single players tests.

https://gist.github.com/Aeron216/e3176114d057179cde30eb53e0302996

https://gist.github.com/Aeron216/7a6f59ab8da9352e372c63b6e0e33a33

Latest log:

https://gist.github.com/Aeron216/504cdbdc85e43c44ce8b39f68cf47d33

Debug log:

https://gist.github.com/Aeron216/5fa00ef1425160b9e9ca44e8c6186299

By the way, are we still fine with running Foamfix along with ASM? Or is Foamfix getting redundant.

Edit:

Seems to happen when loading and unloading certain chunks, because the moment everyone leave the server instantly crashes the same way. Might even be a completely different mod at this point doing bad things.

Edit:

Might be Nether Portal Spread. I'll continue with my tests.

**Comment by Aeron216** [comment]
Had this issue back then in 2019 with Nether Portal Spread.

https://gist.github.com/Aeron216/1241c04796ac049d167bc5a10a3010a4

https://gist.github.com/Aeron216/4de2b8b409eef88aa7fe9104a9665cb5

And this issues started soon after we opened our first Nether portal. I'll have to test if for some time without it. Hopefully this is the culprit.

**Comment by Rongmario** [comment]
Do you have `fasterEntityDataManager` turned on in foamfix's configs?

**Comment by Aeron216** [comment]
It was off. 

Either way I havent been able to reproduce the issue ever since I did something about **Nether Portal Spread** and its library **Collective**.
Closing this now since there wasn't really any problem between Foamfix and ASM.

**Comment by Rongmario** [comment]
Glad to see you found a fix
