### ISSUE TITLE
Incompatibility between VintageFix and SleepingOverhaul

### ISSUE THREAD

**Issue by taisong0612** [LoliKingdom/LoliASM#259]
Installing vintagefix will prevent SleepingOverhaul from accelerating the tickspeed during sleep. 
It seems to be purely between these two, no other mod is necessary to cause this incompatibility.

tested with the latest version of all involved mods + dependencies at:
forge-14.23.5.2847

**Comment by Rongmario** [comment]
You mean just with mixinbooter + loliasm + vintagefix, SleepingOverhaul stops working properly? And this doesn't happen with just mixinbooter + vintagefix + SleepingOverhaul?

Also may I have the log from when this was tested please?

**Comment by taisong0612** [comment]
Okay. The SOH mod stops functioning if Vintagefix is added. CensoredASM is not causing issues with the SOH mod at all.
Here are the logs and results.

log1: Vintage + CensoredASM + SleepingOH
[2024-09-08-1-log1.log.gz](https://github.com/user-attachments/files/16920398/2024-09-08-1-log1.log.gz)
No acceleration 

log2: CensoredASM + SleepingOH
[2024-09-08-2-log2.log.gz](https://github.com/user-attachments/files/16920399/2024-09-08-2-log2.log.gz)
Acceleration, sun rises faster and mobs moving super fast

log3: Vintage + SleepingOH
[2024-09-08-3-log3.log.gz](https://github.com/user-attachments/files/16920400/2024-09-08-3-log3.log.gz)
No acceleration

log4: SleepingOH
[2024-09-08-4-log4.log.gz](https://github.com/user-attachments/files/16920401/2024-09-08-4-log4.log.gz)
Acceleration, same as log2 (Made in Heaven!!!)

**Comment by Rongmario** [comment]
No worries, feel free to link this issue in a new vintagefix issue thread.
