### ISSUE TITLE
Client crash unequipping AS Prism

### ISSUE THREAD

**Issue by Seceroth** [LoliKingdom/LoliASM#26]
When trying to unequip an Astral Sorcery Resplendent Prism the following crash occurs. Client side only, playing on a server.

[crash-2021-09-26_16.08.27-client.txt](https://github.com/LoliKingdom/LoliASM/files/7231518/crash-2021-09-26_16.08.27-client.txt)

Using loliasm-3.0.3.jar and mixinbooter-2.0.jar.

Playing the MCEternal modpack version 1.5.

**Comment by Rongmario** [comment]
Will take a look thanks for the report

**Comment by Rongmario** [comment]
@Seceroth do you have the full log file?

**Comment by Seceroth** [comment]
Sure, here you go:

[2021-09-26-1.log](https://github.com/LoliKingdom/LoliASM/files/7247732/2021-09-26-1.log)

**Comment by Rongmario** [comment]
Since you're playing on a server without LoliASM, you'll have to disable `fixAmuletHolderCapability` as it requires LoliASM to be on both the client and the server. There may be other tweaks in the config needed.

**Comment by Rongmario** [comment]
Closing as there's no followup.
