### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Altodeso** [LoliKingdom/LoliASM#260]
i tried to run the Dimension Zero modpack with Loliasm, MixinBooter and VintageFix.
i also deleted VanillaFix and FoamFix.

[2024-09-11-1.log](https://github.com/user-attachments/files/16972433/2024-09-11-1.log)

**Comment by Rongmario** [comment]
A MixinBooter error, instead of using Phosphor, use Alfheim.

**Comment by Altodeso** [comment]
thanks
