### ISSUE TITLE
Flames are not animated (1.12.2)

### ISSUE THREAD

**Issue by TheControllerOfAUs** [LoliKingdom/LoliASM#262]
Just as I said flames are not animated when using this mod any solutions?

**Comment by TheControllerOfAUs** [comment]
also if it helps I am using v5.20

**Comment by Rongmario** [comment]
Are you using OptiFine, Nothirium or anything similar?

**Comment by TheControllerOfAUs** [comment]
I am using optifine but this issue only happens only happens when this mod is added

**Comment by Microsoft6477** [comment]
YourMinecraftFolder\config\loliasm.cfg

set onDemandAnimatedTextures = false

**Comment by Rongmario** [comment]
Fixed with the mod [Naughthirium](https://www.curseforge.com/minecraft/mc-mods/naughthirium).
