### ISSUE TITLE
3.0+ Incompatible with Dynamic Darkness (Fix: disable packageStringCanonicalization in LoliASM config)

### ISSUE THREAD

**Issue by ALJ323** [LoliKingdom/LoliASM#28]
Last Tested Version that successfully works is LoliASM 2.5 with no issues.
See Attached Log:
https://paste.ee/p/kvjhZ

**Comment by ALJ323** [comment]
Noticed open issue in the other respective git where this was addressed.

**Comment by Rongmario** [comment]
To fix, you can disable `packageStringCanonicalization` in the configs.
