### ISSUE TITLE
Just a crash

### ISSUE THREAD

**Issue by LightDimf** [LoliKingdom/LoliASM#3]
Some strange crash every time I try to load a game with loliasm 2.0.1:
[crash-2021-05-03_19.40.38-client.txt](https://github.com/LoliKingdom/LoliASM/files/6416282/crash-2021-05-03_19.40.38-client.txt)
At first I had crashes with MisticalLib, but I deleted it (and mod related to it) and now I have that issue. 
Also crash-report have some russian words for some reason, so "опустошение стека" == "stack underflow", and "метод" == "method".

**Comment by Rongmario** [comment]
Do you have the full log?

For now, use the 2.0.1 build and turn off `bakedQuadsSquasher` in the config and it should run.

**Comment by LightDimf** [comment]
Here is the full log: 
[debug.log](https://github.com/LoliKingdom/LoliASM/files/6416635/debug.log)
Without `bakedQuadsSquasher ` everything works fine.

**Comment by Rongmario** [comment]
Could you try launching with a [Hotspot installation](https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot)? I just fixed an OpenJ9 bug and wondering if the `VerifyError` is because of OpenJ9 too.

**Comment by ChromaPIE** [comment]
Probably the same type of crash as it: https://paste.dimdev.org/ebowuwokit.mccrash
Full log: https://paste.dimdev.org/jekuketora.md

**Comment by LightDimf** [comment]
Crashes on hotspot too.

**Comment by Rongmario** [comment]
Feel like I've seen this exact error in dev before, but a long time ago. Some other coremod might be redirecting BakedQuads too. Gonna try see what coremods are common in your logs.

**Comment by Rongmario** [comment]
Never mind, fix coming in a bit; though I'm still unsure how this doesn't crash in my environments...

**Comment by Rongmario** [comment]
@LightDimf @ChromaPIE try this build and get back to me (zipped because github doesn't allow jars):
[loliasm-2.0.1.zip](https://github.com/LoliKingdom/LoliASM/files/6418658/loliasm-2.0.1.zip)

**Comment by LightDimf** [comment]
Now there is a crash with CodeChickenLib on loading a world:
[crash-2021-05-04_14.34.43-client.txt](https://github.com/LoliKingdom/LoliASM/files/6420798/crash-2021-05-04_14.34.43-client.txt)

**Comment by Rongmario** [comment]
Full log?

**Comment by LightDimf** [comment]
[Uploading debug.log…]()

**Comment by LightDimf** [comment]
[debug.log](https://github.com/LoliKingdom/LoliASM/files/6420861/debug.log)

**Comment by Rongmario** [comment]
Ah, I don't think Optifine is compatible at the moment, its not a crash with CCL. I will investigate but it would be hard as OF is closed source.

**Comment by Rongmario** [comment]
Closing as of 2.1.
