### ISSUE TITLE
Possible issue with WarpDrive mod

### ISSUE THREAD

**Issue by SilverBackSpartan** [LoliKingdom/LoliASM#34]
[crash-2021-10-20_01.30.08-server.txt](https://github.com/LoliKingdom/LoliASM/files/7380868/crash-2021-10-20_01.30.08-server.txt)

[crash-2021-10-20_02.29.52-server.txt](https://github.com/LoliKingdom/LoliASM/files/7380870/crash-2021-10-20_02.29.52-server.txt)

Happened while trying to warp my ship in space, Spaceship has littleFrames blocks from LittleTiles/CreativeCore mod. Amongst other other blocks from a few mods were placed in close proximity.

**Comment by Rongmario** [comment]
I use LoliASM and WarpDrive constantly and haven't had any issues. Those logs don't seem to have traces of these mods in them?

**Comment by Rongmario** [comment]
No, haven't tried that, but even then, I don't think it'd be a LoliASM issue?

**Comment by SilverBackSpartan** [comment]
I will close this as i dont have proper reports to present this as an issue on your end,.
