### ISSUE TITLE
Use Mixin. Please.

### ISSUE THREAD

**Issue by FreezePhoenix** [LoliKingdom/LoliASM#4]
It would highly help the code of your library, if you used Mixin. It would make fixing it simpler in the future, and many more such things. Please, consider using Mixin. I'm serious. This mod seems like a great idea (Could use a better name? Current one isn't c conducive to it being found on CurseForge) but it seems like it would be hell to maintain.

**Comment by Rongmario** [comment]
How about no? Some of these modifications aren't able to be done with just Mixins. Don't be ridiculous. Get lost.
