### ISSUE TITLE
JEI crashes on startup when installed with JEC

### ISSUE THREAD

**Issue by ChromaPIE** [LoliKingdom/LoliASM#40]
The log and the crash report can be found here: https://github.com/mezz/JustEnoughItems/issues/2546

Everything's not tested. I open the issue here only because of LoliASM being the most sussy one among all mods updated after the latest successful launch.

Edit: Okay I just tried getting back to 3.3, the latest version before that huge JEI-related update, the game booted and now it's guaranteed. So it's only on my end or..?

**Comment by Rongmario** [comment]
Going to reopen, redoing JEI optimizations.

**Comment by Rongmario** [comment]
Closed in https://github.com/LoliKingdom/LoliASM/commit/c2d3b77a51ed8012e386150b3991dcbc0bf0a19f, moving JEI optimization to another mod.
