### ISSUE TITLE
Longer loading times

### ISSUE THREAD

**Issue by Aeron216** [LoliKingdom/LoliASM#44]
Having crashed at all here ever since 4.1.
However, my loading times are now around 10 mins instead of the usual 6 mins. Not sure if thats intended.

4.1 log, 6 mins:

https://gist.github.com/Aeron216/aff1382e21e989e72b5e4c30fb2e8770

4.2.1 logs, 10 mins:

https://gist.github.com/Aeron216/301533d508fd2edbfa73a3d2f0f5d06f

https://gist.github.com/Aeron216/47818bdc33c5d70f1496f57632956292

**Comment by Rongmario** [comment]
Well, your log spams are quite concerning; but it has nothing to do with LoliASM. Everything implemented as of 4.0 is all done away from the main thread...

**Comment by Aeron216** [comment]
Something got scuffed in my instance ever since I updated a batch of mods last night because I just tried older versions of ASM and same long loading times with each one of them. So yeah, I'll close this now. My apologies.

I'll just paste this in here for reference:

Loading times became almost twice as long ever since updating this:
![image](https://user-images.githubusercontent.com/54506307/139558659-74ff1813-360d-44a3-97ab-2e695afd67ff.png)

Last time loading times were fine except for an auto 3rd person view bug:
![image](https://user-images.githubusercontent.com/54506307/139558690-d92cd514-c205-49cd-a09d-7fa30951e048.png)

So I'll still keep updating to the latest versions of ASM because that has nothing to do.

**Comment by Rongmario** [comment]
You can always use LoliASM's spark compat (obviously have to install spark as well) to profile your game load to see which portion of the game is taken up most of the time, that may give you a rough idea of what's going on.

**Comment by Aeron216** [comment]
Changed to true the compat settings in the config but now how do I exactly look at the startup times? I don't have much experience with Spark so I only know how to use it to check for ongoing TPS problems.

**Comment by Rongmario** [comment]
It'll run automatically, look out for links in the log.

**Comment by Aeron216** [comment]
Oh yeah I see it now, thanks.

**Comment by Aeron216** [comment]
The culprit was Music Triggers. Mod alone increased my loading times by a 100% and also breaks resource packs, very unfortunate.

Nice Spark compatibility btw, thanks once again.
