### ISSUE TITLE
MixinBooter is present. Game still crashes.

### ISSUE THREAD

**Issue by MagmaBro123** [LoliKingdom/LoliASM#46]
No other mods are present.

https://pastebin.com/xcMy03ZX

Mod versions in report.

**Comment by Rongmario** [comment]
Will fx in a few days.

**Comment by MagmaBro123** [comment]
Alright.

**Comment by Rongmario** [comment]
Closed in https://github.com/LoliKingdom/LoliASM/commit/c2d3b77a51ed8012e386150b3991dcbc0bf0a19f, moving JEI optimization to another mod.
