### ISSUE TITLE
Breaking Mod-director functionality

### ISSUE THREAD

**Issue by mxnmnm** [LoliKingdom/LoliASM#47]
So I'm using mod director to download optifine from their site, but I've noticed an incompatibility with this mod. In order to get optifine to run on first load you need to do some fancy thing. Here is the wiki page on it https://github.com/Janrupf/mod-director/wiki/Complicated-Mods 

This mod seems to break that somehow, not sure how so here is the log which I'm sure will explain things much better:

https://gist.github.com/mxnmnm/922a4b69dbc7da6f62d2c80c34bc2f32

If you need more info let me know.

**Comment by Rongmario** [comment]
I'll investigate, weird issue
