### ISSUE TITLE
Texture stitching problem with contenttweaker and roost

### ISSUE THREAD

**Issue by bodlosh** [LoliKingdom/LoliASM#49]
This is a very specific one :)
When using this setup on 1.12

forge-1.12.2-14.23.5.2855-universal
CraftTweaker2-1.12-4.1.20.669
base-1.12.2-3.14.0
chickens-6.1.0
ContentTweaker-1.12.2-4.10.0
CraftTweaker2-1.12-4.1.20.669
mixinbooter-2.0
loliasm-4.3
MTLib-3.0.7
modtweaker-4.0.20.5
morechickens-1.12.2-3.2.0
roost-1.12.2-2.0.10

and trying to add a new chickens via contenttweaker like this https://pastebin.com/TDrTyVw9

the game does not load (probably) during texture stitching.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Roost (roost)
Caused by: java.lang.NullPointerException
	at zone.rong.loliasm.bakedquad.LoliVertexDataPool.invalidate(LoliVertexDataPool.java:57)
	at zone.rong.loliasm.proxy.ClientProxy.lambda$releaseSpriteFramesCache$0(ClientProxy.java:103)
....

Without LoliASM the game loads, without adding new chickens the game loads as well.
Full log is here https://paste.ee/p/JzUAl

**Comment by Rongmario** [comment]
Very stupid code from Roost, but I'll guard against it.
