### ISSUE TITLE
Issue - Make a pull request from creative team.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LoliKingdom/LoliASM#5]
com.creativemd.creativecore.client.rendering.model.CreativeBakedQuad needs their BakedQuad calls redirecting! Insert the string into config/loliasm.json and report to Rongmario.

**Comment by Rongmario** [comment]
No need to PR, insert `com.creativemd.creativecore.client.rendering.model.CreativeBakedQuad` into the `bakedQuadPatchClasses` array within `config/loliasm.json`. It'll patch it accordingly.

**Comment by P3rf3ctXZer0** [comment]
Done thank you.
