### ISSUE TITLE
Incompitable with OptiFine (Fluids)

### ISSUE THREAD

**Issue by BlayzerQ** [LoliKingdom/LoliASM#50]
On hover mouse (look) in containers (Drum from ExtraUtlities or any Chest) with fluid from GregTech - (hydrogen, argon, oxygen and other), i get game crash.

Game version: 1.12
Mod version: loliasm-4.3
Optifine version: OptiFine_1.12.2_HD_U_G5

Without OptiFine all fine, crash not happend. And with OptiFine without LoliASM game not crashed.

Logs and config:
[debug.zip](https://github.com/LoliKingdom/LoliASM/files/7503122/debug.zip)

**Comment by Rongmario** [comment]
debug.zip is invalid, can't unzip.

**Comment by BlayzerQ** [comment]
> debug.zip is invalid, can't unzip.

[crash-2021-11-09_10.10.52-client.txt](https://github.com/LoliKingdom/LoliASM/files/7504703/crash-2021-11-09_10.10.52-client.txt)
[latest (1).log](https://github.com/LoliKingdom/LoliASM/files/7504706/latest.1.log)

[debug.log](https://github.com/LoliKingdom/LoliASM/files/7504719/debug.log)
[loliasm.txt](https://github.com/LoliKingdom/LoliASM/files/7504720/loliasm.txt)

**Comment by Rongmario** [comment]
Have you tried using LoliASM without GravitLauncher? I'm using OptiFine right now and not experiencing any problems.

You can try disable `vertexDataCanonicalization` in LoliASM config as well.

**Comment by BlayzerQ** [comment]
> Have you tried using LoliASM without GravitLauncher? I'm using OptiFine right now and not experiencing any problems.
> 
> You can try disable `vertexDataCanonicalization` in LoliASM config as well.

This problem persists on the MultiMC Launcher and TLauncher. Perhaps the matter is in some other modification additionally. What version of OptiFine are you using?

**Comment by Rongmario** [comment]
Tested with both `preview_OptiFine_1.12.2_HD_U_G6_pre1.jar` and `OptiFine_1.12.2_HD_U_G5.jar`. Yeah, try disabling that option and see.

**Comment by Rongmario** [comment]
Invalid atm.
