### ISSUE TITLE
Bug ?

### ISSUE THREAD

**Issue by Kasia1403** [LoliKingdom/LoliASM#51]
[Finalizer/WARN] [LoliASM]: Clearing LoliStringPool 1

**Comment by Rongmario** [comment]
Not a bug, can ignore.

**Comment by Krutoy242** [comment]
What is this means btw? I have same.
Is it means not all functionality working fine?

**Comment by Rongmario** [comment]
It's just logging, you can ignore it. Everything is working fine.
