### ISSUE TITLE
Crash while resource reloading

### ISSUE THREAD

**Issue by ChromaPIE** [LoliKingdom/LoliASM#54]
CR: https://pastebin.com/ZRX1Xn22

Reloading resources with F3+T or saving changes to resourcepack list in game causes the game to crash out to the main menu (VanillaFix installed) and unload all enabled resourcepacks.

**Comment by Rongmario** [comment]
Fixed in https://github.com/LoliKingdom/LoliASM/commit/39c4a94c95eab90db4a9a4f7b2fdddc76d94a779, just haven't bumped release yet.

**Comment by ChromaPIE** [comment]
So are there any planned features delaying the release? I have to frequently reload resources for testing things and now it's kinda like a dilemma and troublesome since I don't want to disable the mod.

**Comment by Rongmario** [comment]
I'll do it later today.
