### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by neymargabo** [LoliKingdom/LoliASM#57]
The game is not launching, the problem is with randompatches or sledgehammer not really sure
[latest.log](https://github.com/LoliKingdom/LoliASM/files/7657724/latest.log) (this is the sponge)
Used the 3 version of sledgehammer (normal, thin and sponge)
Only with the sponge one it doesnt launch
[latest.log](https://github.com/LoliKingdom/LoliASM/files/7657810/latest.log)
This is with the normal and thin
Update: eliminated sledgehammer and vanillafix and the issue was solved

**Comment by Rongmario** [comment]
You don't need to remove them, just update them.
