### ISSUE TITLE
Incompitable with OpenJ9(IBM)

### ISSUE THREAD

**Issue by SakuraRK** [LoliKingdom/LoliASM#59]
I install Loliasm and run in my Minecraft with OpenJ9,Is crash and said "游戏因为使用OpenJ9而崩溃了"(The game crash by OpenJ9).
Then I uninstall it,game started normally.
My error log has losed,so I can'y give it,sry

**Comment by Rongmario** [comment]
安裝Minecraft的資料夾, /log, /crash-report 裡面找的到喔

**Comment by Rongmario** [comment]
Going to close since there's no follow up.
