### ISSUE TITLE
Loading time is increased when cleanupLaunchClassLoader feature is on

### ISSUE THREAD

**Issue by gatoborrachon** [LoliKingdom/LoliASM#6]
*DESCRIPTION*
When i use LoliASM 1.1 (with a personal modpack) it takes 553 seconds to load:
`[21:28:17] [Client thread/INFO] [Surge]: The game loaded in approximately  553.022 seconds.`

But when i used LoliASM 2.1 it took 655:
`[21:16:43] [Client thread/INFO] [Surge]: The game loaded in approximately  655.957 seconds.`

*ADDITIONAL NOTES*
1.- Well, i'm using a personal modpack, so i'm pretty sure that this may be a inter-mod incompatibility, but the possible guilty mods are my performance mods:
![performance](https://user-images.githubusercontent.com/61126174/117091886-50249480-ad22-11eb-94c7-e90c00f2b9cd.PNG)

2.- Tell me if you want my modpack to test it by yourself

**Comment by Rongmario** [comment]
You can disable `cleanupLaunchClassLoader` in the config to decrease the loading time again. I'll change the config comment accordingly. I did some slight tests and it seems like `remapperMemorySaver` doesn't increase by a significant amount.

**Comment by gatoborrachon** [comment]
mmm, i set it as `false` and now the game doesn't even load, inside the Task Manager it says that MC uses 0% of CPU after 2 minutes.

i tried with both OpenJ9 and Hotspot:
![performance](https://user-images.githubusercontent.com/61126174/117094705-1b1c4000-ad2a-11eb-9488-9d3e18f95b00.PNG)

![performance](https://user-images.githubusercontent.com/61126174/117094793-5880cd80-ad2a-11eb-9850-55c147a90621.PNG)

**Comment by Rongmario** [comment]
`Caused by: java.lang.ClassCircularityError: zone/rong/loliasm/api/datastructures/DummyMap`

I'll fix it for next minor build.

**Comment by gatoborrachon** [comment]
yeah sorry, i forgot to upload the log file, but as you said, it is caused by what that line says

Anyways, here is the log: [latest.log](https://github.com/LoliKingdom/LoliASM/files/6424989/latest.log)
