### ISSUE TITLE
Breaking Industrial Foregoing JEI Tabs

### ISSUE THREAD

**Issue by mxnmnm** [LoliKingdom/LoliASM#60]
I tested to see what mod was causing the issue and I realized it was this one.

Here is a previous report I made to another mod author who releases some fixes to industrial foregoing: https://github.com/eve0415/IFPatcher/issues/2

**Comment by Rongmario** [comment]
Try disabling `releaseSpriteFramesCache`

**Comment by v1993** [comment]
> Try disabling `releaseSpriteFramesCache`

Can confirm this this fixes the issue.
