### ISSUE TITLE
Conflict with Custom Main Menu

### ISSUE THREAD

**Issue by superhealing** [LoliKingdom/LoliASM#61]
Looks like new line added hardcoded make to messing up with scale, solution would be a config toggle to disable in case we use custom main menu.

To clarify this how does look with custom main menu:
![image](https://user-images.githubusercontent.com/34381388/147746640-4f082233-e00f-4f91-8dd2-5ed5f2f5c00b.png)

This without:
![image](https://user-images.githubusercontent.com/34381388/147746572-d5d3fa3c-7e04-4198-813e-0edc912914f6.png)

However, there is a way to fix that by modify scaling on custommainmenu config, but that might mess created models for that, since they need to rescale which add additional time.

**Comment by Rongmario** [comment]
This is Custom Main Menu's fault for not accounting for how many lines are in the branding list, no hardcode here.
