### ISSUE TITLE
CodeChickenLib rendering error with chiselsandbits mod

### ISSUE THREAD

**Issue by magcicada** [LoliKingdom/LoliASM#64]
When I chisel a block with chisel, I will get this rendering error: [log](https://pastebin.com/6SCM8qGa)
Mod list:
chiselsandbits-14.33
.mixinbooter-4.1
loliasm-4.4.1
CodeChickenLib-1.12.2-3.2.3.358-universal

**Comment by Rongmario** [comment]
Can you paste the whole log? Also, I recommend using LittleTiles instead.

**Comment by magcicada** [comment]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8061685/latest.log)
The game is running.

**Comment by Rongmario** [comment]
Hmm weird, I'll try check it out but you can disable `squashBakedQuads` in the config.

**Comment by magcicada** [comment]
ok, I will try your suggestion.

**Comment by Rongmario** [comment]
Closing bc of no response.
