### ISSUE TITLE
Multiple Texture glitches

### ISSUE THREAD

**Issue by viqua** [LoliKingdom/LoliASM#65]
when using the mod i had major problem with textures?

-a lot of machine from thermal appear as glitch (purple/black textureless cube)
-AE2 sceen appear as grey (no color or texture)
-Extra utilities 2 drums doesn't get the fluids's colors anymore (they stay grey as if there were empty)

note: it happened to me but one of my friend with the mod, on the same modpack and server didn't had those bugs

how do i fix this?

**Comment by embeddedt** [comment]
I've had these issues sporadically in the past; I used to work around them by relaunching the game but I haven't needed to do that in a long time. [Here](https://gist.github.com/embeddedt/be1ed1d1a981f6ff4e6aaead337b353b) is the config file I use in case it helps. I turned off some settings based on suggestions in various issues to fix mod incompatibilities.

**Comment by Rongmario** [comment]
What happens is, on the first load there is no information about where certain calls reside. The call is monitored and it is added to the config list if fired. 

On the next load, the config list is read and the classes are transformed to change the calls. I didn't want to arbitrarily transform all classes and scan through as it is detrimental to the load time.

All in all, reload the game and it'll work.
