### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [LoliKingdom/LoliASM#67]
Make LoliASM independent of Spark, because of theese crashes :

[crash-2022-04-14_18.31.04-client.txt](https://github.com/LoliKingdom/LoliASM/files/8490923/crash-2022-04-14_18.31.04-client.txt)

[crash-2022-04-14_18.31.03-client.txt](https://github.com/LoliKingdom/LoliASM/files/8490924/crash-2022-04-14_18.31.03-client.txt)

And because I don't like Spark mod.

**Comment by Rongmario** [comment]
Spark isn't a needed dependency, and LoliASM really only supports Spark 1.5.2.

**Comment by Kasia1403** [comment]
Sorry, but in theese 2 crash reports that I posted yesterday it was written something about Spark and Minecraft didn't start. Minecraft started when I added Spark. Maybe it is a bug ?

**Comment by Rongmario** [comment]
Ah, that's because you have `sparkSummarizeHeapSpaceAfterGameLoads` set to true, but I'll sanity check so it doesn't run if you don't have Spark installed.
