### ISSUE TITLE
[1.12.2] Conflict with Immersive Engineering. ASM deletes items in the IM Tool Box.

### ISSUE THREAD

**Issue by Z-Tunic** [LoliKingdom/LoliASM#71]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 
!mixinbooter-4.2
[___MixinCompat-0.8___]
HadEnoughItems_1.12.2-4.20.1
ImmersiveEngineering-0.12-98
loliasm-4.10

=====

"loliasm-4.10" has a bit of a conflict where it breaks the IM Tool Box. Any items put inside the Tool Box will appear to work nromally but the moment you move the tool box somewhere else in your inventory slot... it's contents are wiped clean.

![asmclearingtoolbox](https://user-images.githubusercontent.com/36653806/164853845-fd805051-8c81-4b78-9307-d1f06e0cd8df.png)
Left: Tool Box filled with a bunch of items.
Right: Moved the Tool Box 1 slot to the right, opened it... and my items are gone.

This didn't happen when using "loliasm-4.8" as no items inside the Tool Box were wiped clean. Unsure if this affects other internal storage items, such as the Bag of Holding from Extra Ultities 2, Project E's Alchemy Bag, etc.

**Comment by Rongmario** [comment]
`latest.log` and `debug.log` please, it could be the capability stuff we tried to optimize.

**Comment by Rongmario** [comment]
You can attempt to fix this by turning `delayItemStackCapabilityInit` off. That's what I suspect atm.

**Comment by Z-Tunic** [comment]
Latest & Debug Logs, had to put items inside the Tool Box and move it to another slot so it could delete them.

[latest.log](https://github.com/LoliKingdom/LoliASM/files/8545782/latest.log)

[debug.log](https://github.com/LoliKingdom/LoliASM/files/8545783/debug.log)

=====

Set "delayItemStackCapabilityInit" to false, and items in the Tool Box weren't deleted when I moved it to a different slot in my inventory.

**Comment by Rongmario** [comment]
Nothing seems to be wrong in the logs, we'll check through the stuff we did for `delayItemStackCapabilityInit`. Thanks for the report.

**Comment by Aeron216** [comment]
I can confirm the same thing happening with 4.9 and Spartan Weaponry quivers.

https://gfycat.com/tediousdisguisedicelandicsheepdog

[latest](https://gist.github.com/Aeron216/6f7dfebabd31d63e49a28467f83f6eb4)

[debug](https://gist.github.com/Aeron216/1c0c52950eddaebbf2d1d40c7e50426f)

And just as said, with `delayItemStackCapabilityInit` set to false it stops happening.

https://gfycat.com/equalthirdboutu

[latest](https://gist.github.com/Aeron216/68583e0d82bc0e6bdfec170e81ec8f33)

[debug](https://gist.github.com/Aeron216/2bc6abe63f0acb2986ea93bc8dbf0081)

**Comment by Aeron216** [comment]
My bad, I didn't realize there was a new version now (4.10). Now I am away from my computer, however I had also tried 4.8 and even with `delayItemStackCapabilityInit` set to true the quiver items were fine.

**Comment by Z-Tunic** [comment]
> My bad, I didn't realize there was a new version now (4.10), now I am away from my computer. By the way I had also tried 4.8 and even with `delayItemStackCapabilityInit` set to true the quiver items were fine.

Yea, with 4.8 the bug didn't occur, also `delayItemStackCapabilityInit` wasn't in 4.8 as that got added in 4.9+... at least when checking the config file before updating.

If you ran 4.10 first, that option gets added to the config. Should you downgrade... the option will still be there but it won't do anything.

**Comment by Aeron216** [comment]
> > My bad, I didn't realize there was a new version now (4.10), now I am away from my computer. By the way I had also tried 4.8 and even with `delayItemStackCapabilityInit` set to true the quiver items were fine.
> 
> Yea, with 4.8 the bug didn't occur, also `delayItemStackCapabilityInit` wasn't in 4.8 as that got added in 4.9+... at least when checking the config file before updating.
> 
> If you ran 4.9 / 4.10 first, that option gets added to the config. Should you downgrade to 4.8 or lower... the option will still be there but it won't do anything.

You are absolutely right.

**Comment by Z-Tunic** [comment]
The bug still occurs, using... `loliasm-4.10.4`.

If you put items inside the tool box, then move it to your inventory (Not the hotbar), leave & rejoin the world... moving the tool box to your hotbar... and upon opening it... my items were gone.

[latest.log](https://github.com/LoliKingdom/LoliASM/files/8551396/latest.log)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8551397/debug.log)

It does not occur if you move the Tool Box within your Hotbar and open it, it only bugs out if you have the toolbox in your inventory upon leaving the world.

`delayItemStackCapabilityInit` set to false avoids the bug.
