### ISSUE TITLE
Spark profiling not working

### ISSUE THREAD

**Issue by freopt** [LoliKingdom/LoliASM#72]
![image](https://user-images.githubusercontent.com/45438411/164868290-bb124c8c-eff8-4307-8dfe-2a8fa1a5fdf5.png)
spark 1.5.2
loliasm 4.10
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8545971/latest.log)

**Comment by Rongmario** [comment]
Try without OpenJ9 and/or use other launchers instead of GDLauncher. GD has been experiencing weird duplicated mods issues recently.

**Comment by freopt** [comment]
it works with multimc

**Comment by Rongmario** [comment]
Might need to tell the GDLauncher guys, weird stuff.

**Comment by freopt** [comment]
When I enable spark compat, where do I get the results of the profiling? It says it's starting profiling in the log but the game finishes loading and there's no result

**Comment by Rongmario** [comment]
URL to the profiled results should show up in the logs too

**Comment by freopt** [comment]
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8548377/latest.log)
no urls here

**Comment by Rongmario** [comment]
Something is wrong yep, I'll push a release later in the day.
