### ISSUE TITLE
[1.12.2] Exception in world tick - "recheckGapsGetLowestHeight" - Need help

### ISSUE THREAD

**Issue by aking4125** [LoliKingdom/LoliASM#74]
Hello,

I understand that this issue isn't related to [LoliASM](https://www.curseforge.com/minecraft/mc-mods/lolasm) at all but I am running out of options and I cannot pinpoint the exact cause of this problem but here is the gist.

**This only applies to the client.** Upon exploring the world, the client would crash with below crash error. Upon reloading into the server or world 80% of the time the client is stuck on a crash loop until the player TP's out of that position. For some reason this seems to affect only a few players at a time in random locations but those locations become "Crash zones" for the players until the server restarts. Once it restarts, they are free to enter the area, but then crashes upon entering another random chunk. Sometimes it's right next to their base.

The only clue I got is upon entering the kill command to destroy all entities. The crash stops for a bit. So it might just be an entity though only once did this not fix the problem. However the kill command must be performed while in a world. So a second player is required to save the other each time. Restarting the server is the temp fix but random locations gets affected again. This is a very annoying problem and I never experienced this in 1.12.2 before. Any ideas or a clue or a point in the right direction would be greatly appreciated. This occurs in both Single player and Multiplayer but the server itself doesn't crash. Only the client.

Client Crash Report: [crash-2022-04-24_09.56.18-client.txt](https://github.com/LoliKingdom/LoliASM/files/8549829/crash-2022-04-24_09.56.18-client.txt)
[Client Debug Log](https://www.mediafire.com/file/zrfxxj3ujdgkjr4/debug.log/file)
[Modpack files](https://www.mediafire.com/file/e13mwfs72ad4ivi/modpack_-_aking4125.zip/file)

Again, any ideas or a clue or a point in the right direction would be greatly appreciated!

**Comment by Rongmario** [comment]
Thanks for the report, this is actually a crash from `Fluidlogging API`: https://github.com/jbredwards/Fluidlogged-API/issues/75, I believe a fix is being worked on.

**Comment by aking4125** [comment]
Thank you for the instant response!
