### ISSUE TITLE
1.10.3 doesn't let the game load

### ISSUE THREAD

**Issue by brisingraerowing** [LoliKingdom/LoliASM#75]
[Game Output](https://gist.github.com/brisingraerowing/b0925dd8d4c8991e0978bd849e98dfe9)

I'm presuming this is a compat issue with another mod. I have almost 400 mods in this pack, so finding the culprit might be annoying.

**Comment by Rongmario** [comment]
Might need a debug log if you got one.

**Comment by brisingraerowing** [comment]
Added the debug log to the Gist.

**Comment by brisingraerowing** [comment]
One of the recent fixes seems to have fixed this issue as well.
