### ISSUE TITLE
4.10.5 crashes Binne's Extra Trees

### ISSUE THREAD

**Issue by brisingraerowing** [LoliKingdom/LoliASM#77]
[Crash Log](https://gist.github.com/brisingraerowing/0bdd58c34230417c61014466068818cd)

**Comment by Rongmario** [comment]
Full log please, looks like an absurd error...

**Comment by brisingraerowing** [comment]
Added game output and debug logs to the gist.

**Comment by Rongmario** [comment]
Can you try if turning `delayItemStackCapabilityInit` off would solve this?

**Comment by Rongmario** [comment]
Need a follow up for the Techguns crash.

**Comment by brisingraerowing** [comment]
That pack is currently non-functional, so it might be a bit. Should I make a new issue for it?

**Comment by Rongmario** [comment]
Sure!
