### ISSUE TITLE
Incompatible with latest Spark

### ISSUE THREAD

**Issue by Krutoy242** [LoliKingdom/LoliASM#78]
Got crash on game load.
[Latest spark for 1.12](https://www.curseforge.com/minecraft/mc-mods/spark/files/3542217).

![image](https://user-images.githubusercontent.com/936618/165142241-33d2e2ff-26dd-4ed1-bafb-ea38b8079571.png)

Its nice that it tells, that i have wrong Spark, but, why this even an issue? I just checked out mod description on CF and patch notes - mentions nothing about Spark version.

[debug.log](https://github.com/LoliKingdom/LoliASM/files/8556752/debug.log)

**Comment by Rongmario** [comment]
Latest Spark is broken, hence why you have to use 1.5.2. Also it is listed in this changelog: https://www.curseforge.com/minecraft/mc-mods/lolasm/files/3763635

> - If you're using Spark, you must use **Spark 1.5.2**, the new version is borked

**Comment by Krutoy242** [comment]
Oops, seems like missed this one.
