### ISSUE TITLE
[1.12.2] Conflict with Treasure2. Weird stacking issue with Diamonds & Emeralds + A random crash upon startup.

### ISSUE THREAD

**Issue by Z-Tunic** [LoliKingdom/LoliASM#79]
===Bug 1===
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 6
!mixinbooter-4.2
[___MixinCompat-0.8___]
GottschCore-mc1.12.2-f14.23.5.2859-v1.15.0
HadEnoughItems_1.12.2-4.20.1
loliasm-4.11
Treasure2-mc1.12.2-f14.23.5.2859-v2.0.1

---

For some reason... if you have Treasure 2 installed alongside with ASM... Diamonds & Emeralds won't stack correctly and instead will fill up in your inventory as separate items... unless the dropped diamonds/emeralds were stacked already... though you can brute force the items together which in due time... they will stack.

This also happens when you pull the items from jei's with cheat mode enabled. If 'mouse_pickup'... you will only get 1 diamond/emerald upon clicking them no matter how many times you click on them. If 'inventory' is selected... diamonds/emeralds will fill each separate slot in your hotbar/inventory as you click on them.

If `delayItemStackCapabilityInit` is set to false. Diamonds & Emeralds will stack correctly as they should without them filling your slots separately as well as jei's cheat menu stacking the items correctly.

===Bug 2===
[crash-2022-04-25_20.42.57-client.txt](https://github.com/LoliKingdom/LoliASM/files/8559180/crash-2022-04-25_20.42.57-client.txt)

A random crash can occur upon startup, although if you had vanillafix installed... you can bypass the crash with it closing the game and still load the menu & select a world.

In the crash report with the above mods... I had Xaero's Minimap & Worldmap and those have a screen that appears upon startup if there's an update available. I wonder if perhaps maybe that might be linked to the crash occurring? At time of this post those mods are the current version.

**Comment by Rongmario** [comment]
Fixes bug no. 2 in efa145878d803f87816d7ccb32578ece631debad, will attempt to solve first bug now.
