### ISSUE TITLE
Crashing other mods

### ISSUE THREAD

**Issue by Aeron216** [LoliKingdom/LoliASM#8]
I tried with three different new worlds and they always ended up crashing within seconds.

https://gist.github.com/Aeron216/c2d32f18a3002bc93ab20d87b9c036e7

https://gist.github.com/Aeron216/bd21207222f7ca4d2881d624f14f9b99

https://gist.github.com/Aeron216/580949991224f3b95c4912b598e79e77

This was with **loliasm-2.2**

Stopped crashing after removing the mod.

Mod list:

https://gist.github.com/Aeron216/1712d3358cb0df08c81d97e631e31933

**Comment by Rongmario** [comment]
Not at my pc right now but FastFurnace is made obsolete with `optimizeFurnaceRecipes`. But I'll take a look at the crashes later on in the day. Thanks for reporting.

**Comment by Rongmario** [comment]
Also, it'd be nice if you can post `latest.log` and `debug.log` from the runs when you crashed.

**Comment by Aeron216** [comment]
Crash
https://gist.github.com/Aeron216/2272bb6e0e342b8c6a3e0b1469b0f99f
[crash-2021-05-08_05.31.33-server.txt](https://github.com/LoliKingdom/LoliASM/files/6445698/crash-2021-05-08_05.31.33-server.txt)

latest
https://gist.github.com/Aeron216/8d20bf4fac8b034a841d14a724d1c70f
[latest.log](https://github.com/LoliKingdom/LoliASM/files/6445699/latest.log)

debug
https://gist.github.com/Aeron216/0dd7f18b1e30aa175c8e4ae22a1e9201
debug.log is too big for a post here (34 MB)
