### ISSUE TITLE
Crash with Hbm's Nuclear Tech Mod Reloaded

### ISSUE THREAD

**Issue by Zephyriumtdw** [LoliKingdom/LoliASM#80]
Crashes on startup

Mods:
[hbm-1.6.5a-G.jar](https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-reloaded/files/3761706)
loliasm-4.11.1.jar
!mixinbooter-4.2.jar

forge-1.12.2-14.23.5.2860

[Crash Log](https://gist.github.com/Zephyriumtdw/e0fe66731dc97dff9a4e5959a6a921fc)
[Log](https://gist.github.com/Zephyriumtdw/4522a81a7d7d4dbd2b9fdc0619fdbc15)

Versions of LoliASM below 4.11 works normaly.

**Comment by wed15** [comment]
I'm also getting same crash after updating to 4.11.1 too, but with different mods. From the logs I tested with several mods with custom fluids which also registered as Forge bucket(?), and found these mods each causing the same crash:
- BiomesOPlenty-1.12.2-7.0.1.2444-universal
- Minestrappolation.5.8.0.Pre.2-e
- Inspirations-1.12.2-0.2.9
- stygian-1.0.4
- theaurorian-1.12.2-release-may3021
These are not every mod causing the problems in my instance, but give up finding all of them.

Logs made with Loiliasm 4.11.1 and these mods:
[crash-2022-03-31_02.04.26-client.txt](https://github.com/LoliKingdom/LoliASM/files/8564962/crash-2022-03-31_02.04.26-client.txt)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8564957/latest.log)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8564958/debug.log)

Not every mod with custom Forge fluid bucket are causing crashes though. Some of them seem to be loaded fine with Loliasm.
- LeatherWorks-1.12-1.78.0.42
- twilightforest-1.12.2-3.11.1020-universal

**Comment by Rongmario** [comment]
I can't recreate any of this with HBM or other mods, very weird.

**Comment by kappa-maintainer** [comment]
Same here, crashed after update, have to set reuseBucketQuads=false to launch the game

**Comment by Rongmario** [comment]
I have no idea how and where I fixed it, try it out before I upload on CF:
[loliasm-4.12.zip](https://github.com/LoliKingdom/LoliASM/files/8565381/loliasm-4.12.zip)

**Comment by wed15** [comment]
Tested on my modpack and fresh instance, the crash don't occur and every Forge bucket looks and functions with out any problem in game.
