### ISSUE TITLE
[4.13 - 1.12.2] Server reporting Duplicates of Loliasm-4.13 when there's only 1 file in the folder

### ISSUE THREAD

**Issue by aking4125** [LoliKingdom/LoliASM#82]
Hello,

Upon upgrading from 4.12 to 4.13. The server crashed with the following crash report thinking there are two of the same jar files in the folder when there's just one. This occurs with just mixinbooter and loliasm-4.13. [crash-2022-04-28_00.06.05-server.txt](https://github.com/LoliKingdom/LoliASM/files/8579425/crash-2022-04-28_00.06.05-server.txt)

![image](https://user-images.githubusercontent.com/11141831/165674824-e7279f1b-3bd5-4ca4-bc83-322d885c3383.png)

4.12 works perfectly fine. This issue doesn't show up on the single-player client for some reason, however. Any ideas?

**Comment by Rongmario** [comment]
I tried a different parameter when I built the jar file, theres been a bug among various mods that uses mixins and I'm trying to debug it. Thanks for the report.

**Comment by Aeron216** [comment]
Here to report the same.

![image](https://user-images.githubusercontent.com/54506307/165742908-91c84d7a-82eb-46c7-9a12-06797e4b4cd9.png)
