### ISSUE TITLE
crash when i looked at a bibliocraft framed chest

### ISSUE THREAD

**Issue by xemnes** [LoliKingdom/LoliASM#85]
pretty much the title, though unsure if this is the cause.
i was whitelisting chest blocks to fluidlogged api so that they can be waterlogged
placed down some water on the framed chests from bibliocraft, then i moved back a bit and then i crashed about 10 seconds later
heres the crash report: https://pastebin.com/fP64M0Tb

**Comment by embeddedt** [comment]
This looks like the same issue as #84 and should be fixed in the next release.

**Comment by Rongmario** [comment]
Yep, same issue.

**Comment by xemnes** [comment]
ah sorry about that, i did a search for the first line of the stacktrace but i got no results.
