### ISSUE TITLE
Crash with Wings mod on startup

### ISSUE THREAD

**Issue by PossiblyADuck** [LoliKingdom/LoliASM#9]
2.2 doesn't crash but 2.2.1 and 2.3 crashes with Wings mod on startup with "optimizeDataStructures": true
https://www.curseforge.com/minecraft/mc-mods/wings/files/2829351
https://www.curseforge.com/minecraft/mc-mods/llibrary/files/3116493

Modlist:
loliasm-2.3
wings-1.1.6-1.12.2
llibrary-1.7.20-1.12.2
[crash-2021-05-08_22.46.50-client.txt](https://github.com/LoliKingdom/LoliASM/files/6446868/crash-2021-05-08_22.46.50-client.txt)

**Comment by Rongmario** [comment]
Do you have the full log? It seems like one of the mixins aren't being applied, I also can't reproduce it in any of my modded instances for some reason.

**Comment by Rongmario** [comment]
`[mixin]: Critical problem: mixins.memory.json:ModCandidateMixin target net.minecraftforge.fml.common.discovery.ModCandidate was loaded too early.`

I'll launch with Wings+LLibrary in the morning, thanks for the log file.

**Comment by PossiblyADuck** [comment]
Ty for trying to fix in 2.3.1. Made new instance, added 2.3.1, added mixinbooter 1.1 and is still getting the crash with wings mod with "optimizeDataStructures": true

Is happily using 2.2 so no need to rush and fix :3


[crash-2021-05-11_14.54.30-client.txt](https://github.com/LoliKingdom/LoliASM/files/6461395/crash-2021-05-11_14.54.30-client.txt)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/6461400/debug.log)
