### ISSUE TITLE
[ASM VerifyError] loliasm 5.0 is incompatible with B3M

### ISSUE THREAD

**Issue by kappa-maintainer** [LoliKingdom/LoliASM#90]
[Crash Report](https://gist.github.com/kappa-maintainer/983035421a3740afbc1b5ab292bd1e26)

**Comment by Rongmario** [comment]
B3M is a coremod?

**Comment by kappa-maintainer** [comment]
Yes, it provides some kind of hardcore darkness function by asming into EntityRenderer's nightvision method and many render classes

**Comment by Rongmario** [comment]
Can you try disabling either `fixMC30845` or `fixMC31681` to see which is causing it?

**Comment by kappa-maintainer** [comment]
Fix31681 caused this. Is it possible to make mixin compatible with asm? If not, I guess I have to disable the fix

**Comment by Rongmario** [comment]
Does this build work for you? [loliasm-5.1.zip](https://github.com/LoliKingdom/LoliASM/files/8640061/loliasm-5.1.zip)

**Comment by kappa-maintainer** [comment]
Yes, and the B3M conflict seems fixed
