### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [LoliKingdom/LoliASM#97]
To add compatibility with VanillaFix.

**Comment by Rongmario** [comment]
VF is redundant as of v5.

**Comment by Kasia1403** [comment]
> VF is redundant as of v5.

Could You explain me why ? I would like to have both mods for optimalisations / optimalizations and also VanillaFix for crashing without quitting game.

**Comment by Rongmario** [comment]
99% of VF is included and improved in LoliASM. That's why VF is redundant as of v5.

**Comment by Kasia1403** [comment]
So what's not included ( from VanillaFix ) ?
