### ISSUE TITLE
Mod doesn't work properly with resource loader, leading to animated textures not work

### ISSUE THREAD

**Issue by TheNelston** [LoliKingdom/LoliASM#99]
Title says it all, the mod prevents textures with associated .mcmeta files from working properly. Thank you for any help!

**Comment by Rongmario** [comment]
Log

**Comment by TheNelston** [comment]
which log? just latest.log?

**Comment by MasterEnderman** [comment]
The same happens with the animation of avaritia items. 
```
# Calculate and send animated textures only when needed to the GPU, better than VanillaFix's textureFixes config - <default: true>
    B:onDemandAnimatedTextures=false
```
turning off fixes it.

**Comment by Rongmario** [comment]
Latest/debug log, either or both

**Comment by TheNelston** [comment]
[debug.log](https://github.com/LoliKingdom/LoliASM/files/8673251/debug.log)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/8673252/latest.log)

**Comment by Rongmario** [comment]
Closing to make #113 the main `onDemandAnimatedTextures` thread.
